import { PrimitiveProps } from '@grape-design/react-primitive';
import * as react from 'react';

type LoadingStatus = "loading" | "loaded" | "error";
interface UseAvatarStateProps {
    onLoadingStatusChange?: (status: LoadingStatus) => void;
}
interface UseAvatarProps extends UseAvatarStateProps {
}
type UseAvatarReturn = ReturnType<typeof useAvatar>;
declare function useAvatar(props: UseAvatarProps): {
    refs: {
        image: react.MutableRefObject<HTMLImageElement>;
    };
    loadingStatus: LoadingStatus;
    stateProps: {
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: react.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: react.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        exportparts?: string | undefined;
        part?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        children?: react.ReactNode | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: react.ClipboardEventHandler<HTMLElement>;
        onCopyCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCut?: react.ClipboardEventHandler<HTMLElement>;
        onCutCapture?: react.ClipboardEventHandler<HTMLElement>;
        onPaste?: react.ClipboardEventHandler<HTMLElement>;
        onPasteCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCompositionEnd?: react.CompositionEventHandler<HTMLElement>;
        onCompositionEndCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStart?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStartCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdate?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdateCapture?: react.CompositionEventHandler<HTMLElement>;
        onFocus?: react.FocusEventHandler<HTMLElement>;
        onFocusCapture?: react.FocusEventHandler<HTMLElement>;
        onBlur?: react.FocusEventHandler<HTMLElement>;
        onBlurCapture?: react.FocusEventHandler<HTMLElement>;
        onChange?: react.FormEventHandler<HTMLElement>;
        onChangeCapture?: react.FormEventHandler<HTMLElement>;
        onBeforeInput?: react.InputEventHandler<HTMLElement>;
        onBeforeInputCapture?: react.FormEventHandler<HTMLElement>;
        onInput?: react.FormEventHandler<HTMLElement>;
        onInputCapture?: react.FormEventHandler<HTMLElement>;
        onReset?: react.FormEventHandler<HTMLElement>;
        onResetCapture?: react.FormEventHandler<HTMLElement>;
        onSubmit?: react.FormEventHandler<HTMLElement>;
        onSubmitCapture?: react.FormEventHandler<HTMLElement>;
        onInvalid?: react.FormEventHandler<HTMLElement>;
        onInvalidCapture?: react.FormEventHandler<HTMLElement>;
        onLoad?: react.ReactEventHandler<HTMLElement>;
        onLoadCapture?: react.ReactEventHandler<HTMLElement>;
        onError?: react.ReactEventHandler<HTMLElement>;
        onErrorCapture?: react.ReactEventHandler<HTMLElement>;
        onKeyDown?: react.KeyboardEventHandler<HTMLElement>;
        onKeyDownCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPress?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPressCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUp?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUpCapture?: react.KeyboardEventHandler<HTMLElement>;
        onAbort?: react.ReactEventHandler<HTMLElement>;
        onAbortCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlay?: react.ReactEventHandler<HTMLElement>;
        onCanPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThrough?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThroughCapture?: react.ReactEventHandler<HTMLElement>;
        onDurationChange?: react.ReactEventHandler<HTMLElement>;
        onDurationChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onEmptied?: react.ReactEventHandler<HTMLElement>;
        onEmptiedCapture?: react.ReactEventHandler<HTMLElement>;
        onEncrypted?: react.ReactEventHandler<HTMLElement>;
        onEncryptedCapture?: react.ReactEventHandler<HTMLElement>;
        onEnded?: react.ReactEventHandler<HTMLElement>;
        onEndedCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedData?: react.ReactEventHandler<HTMLElement>;
        onLoadedDataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadata?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadStart?: react.ReactEventHandler<HTMLElement>;
        onLoadStartCapture?: react.ReactEventHandler<HTMLElement>;
        onPause?: react.ReactEventHandler<HTMLElement>;
        onPauseCapture?: react.ReactEventHandler<HTMLElement>;
        onPlay?: react.ReactEventHandler<HTMLElement>;
        onPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onPlaying?: react.ReactEventHandler<HTMLElement>;
        onPlayingCapture?: react.ReactEventHandler<HTMLElement>;
        onProgress?: react.ReactEventHandler<HTMLElement>;
        onProgressCapture?: react.ReactEventHandler<HTMLElement>;
        onRateChange?: react.ReactEventHandler<HTMLElement>;
        onRateChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeked?: react.ReactEventHandler<HTMLElement>;
        onSeekedCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeking?: react.ReactEventHandler<HTMLElement>;
        onSeekingCapture?: react.ReactEventHandler<HTMLElement>;
        onStalled?: react.ReactEventHandler<HTMLElement>;
        onStalledCapture?: react.ReactEventHandler<HTMLElement>;
        onSuspend?: react.ReactEventHandler<HTMLElement>;
        onSuspendCapture?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdate?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdateCapture?: react.ReactEventHandler<HTMLElement>;
        onVolumeChange?: react.ReactEventHandler<HTMLElement>;
        onVolumeChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onWaiting?: react.ReactEventHandler<HTMLElement>;
        onWaitingCapture?: react.ReactEventHandler<HTMLElement>;
        onAuxClick?: react.MouseEventHandler<HTMLElement>;
        onAuxClickCapture?: react.MouseEventHandler<HTMLElement>;
        onClick?: react.MouseEventHandler<HTMLElement>;
        onClickCapture?: react.MouseEventHandler<HTMLElement>;
        onContextMenu?: react.MouseEventHandler<HTMLElement>;
        onContextMenuCapture?: react.MouseEventHandler<HTMLElement>;
        onDoubleClick?: react.MouseEventHandler<HTMLElement>;
        onDoubleClickCapture?: react.MouseEventHandler<HTMLElement>;
        onDrag?: react.DragEventHandler<HTMLElement>;
        onDragCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnd?: react.DragEventHandler<HTMLElement>;
        onDragEndCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnter?: react.DragEventHandler<HTMLElement>;
        onDragEnterCapture?: react.DragEventHandler<HTMLElement>;
        onDragExit?: react.DragEventHandler<HTMLElement>;
        onDragExitCapture?: react.DragEventHandler<HTMLElement>;
        onDragLeave?: react.DragEventHandler<HTMLElement>;
        onDragLeaveCapture?: react.DragEventHandler<HTMLElement>;
        onDragOver?: react.DragEventHandler<HTMLElement>;
        onDragOverCapture?: react.DragEventHandler<HTMLElement>;
        onDragStart?: react.DragEventHandler<HTMLElement>;
        onDragStartCapture?: react.DragEventHandler<HTMLElement>;
        onDrop?: react.DragEventHandler<HTMLElement>;
        onDropCapture?: react.DragEventHandler<HTMLElement>;
        onMouseDown?: react.MouseEventHandler<HTMLElement>;
        onMouseDownCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseEnter?: react.MouseEventHandler<HTMLElement>;
        onMouseLeave?: react.MouseEventHandler<HTMLElement>;
        onMouseMove?: react.MouseEventHandler<HTMLElement>;
        onMouseMoveCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOut?: react.MouseEventHandler<HTMLElement>;
        onMouseOutCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOver?: react.MouseEventHandler<HTMLElement>;
        onMouseOverCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseUp?: react.MouseEventHandler<HTMLElement>;
        onMouseUpCapture?: react.MouseEventHandler<HTMLElement>;
        onSelect?: react.ReactEventHandler<HTMLElement>;
        onSelectCapture?: react.ReactEventHandler<HTMLElement>;
        onTouchCancel?: react.TouchEventHandler<HTMLElement>;
        onTouchCancelCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchEnd?: react.TouchEventHandler<HTMLElement>;
        onTouchEndCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchMove?: react.TouchEventHandler<HTMLElement>;
        onTouchMoveCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchStart?: react.TouchEventHandler<HTMLElement>;
        onTouchStartCapture?: react.TouchEventHandler<HTMLElement>;
        onPointerDown?: react.PointerEventHandler<HTMLElement>;
        onPointerDownCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerMove?: react.PointerEventHandler<HTMLElement>;
        onPointerMoveCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerUp?: react.PointerEventHandler<HTMLElement>;
        onPointerUpCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerCancel?: react.PointerEventHandler<HTMLElement>;
        onPointerCancelCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerEnter?: react.PointerEventHandler<HTMLElement>;
        onPointerLeave?: react.PointerEventHandler<HTMLElement>;
        onPointerOver?: react.PointerEventHandler<HTMLElement>;
        onPointerOverCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerOut?: react.PointerEventHandler<HTMLElement>;
        onPointerOutCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onScroll?: react.UIEventHandler<HTMLElement>;
        onScrollCapture?: react.UIEventHandler<HTMLElement>;
        onWheel?: react.WheelEventHandler<HTMLElement>;
        onWheelCapture?: react.WheelEventHandler<HTMLElement>;
        onAnimationStart?: react.AnimationEventHandler<HTMLElement>;
        onAnimationStartCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEnd?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEndCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIteration?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIterationCapture?: react.AnimationEventHandler<HTMLElement>;
        onTransitionEnd?: react.TransitionEventHandler<HTMLElement>;
        onTransitionEndCapture?: react.TransitionEventHandler<HTMLElement>;
    };
    rootProps: {
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: react.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: react.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        exportparts?: string | undefined;
        part?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        children?: react.ReactNode | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: react.ClipboardEventHandler<HTMLElement>;
        onCopyCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCut?: react.ClipboardEventHandler<HTMLElement>;
        onCutCapture?: react.ClipboardEventHandler<HTMLElement>;
        onPaste?: react.ClipboardEventHandler<HTMLElement>;
        onPasteCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCompositionEnd?: react.CompositionEventHandler<HTMLElement>;
        onCompositionEndCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStart?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStartCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdate?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdateCapture?: react.CompositionEventHandler<HTMLElement>;
        onFocus?: react.FocusEventHandler<HTMLElement>;
        onFocusCapture?: react.FocusEventHandler<HTMLElement>;
        onBlur?: react.FocusEventHandler<HTMLElement>;
        onBlurCapture?: react.FocusEventHandler<HTMLElement>;
        onChange?: react.FormEventHandler<HTMLElement>;
        onChangeCapture?: react.FormEventHandler<HTMLElement>;
        onBeforeInput?: react.InputEventHandler<HTMLElement>;
        onBeforeInputCapture?: react.FormEventHandler<HTMLElement>;
        onInput?: react.FormEventHandler<HTMLElement>;
        onInputCapture?: react.FormEventHandler<HTMLElement>;
        onReset?: react.FormEventHandler<HTMLElement>;
        onResetCapture?: react.FormEventHandler<HTMLElement>;
        onSubmit?: react.FormEventHandler<HTMLElement>;
        onSubmitCapture?: react.FormEventHandler<HTMLElement>;
        onInvalid?: react.FormEventHandler<HTMLElement>;
        onInvalidCapture?: react.FormEventHandler<HTMLElement>;
        onLoad?: react.ReactEventHandler<HTMLElement>;
        onLoadCapture?: react.ReactEventHandler<HTMLElement>;
        onError?: react.ReactEventHandler<HTMLElement>;
        onErrorCapture?: react.ReactEventHandler<HTMLElement>;
        onKeyDown?: react.KeyboardEventHandler<HTMLElement>;
        onKeyDownCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPress?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPressCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUp?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUpCapture?: react.KeyboardEventHandler<HTMLElement>;
        onAbort?: react.ReactEventHandler<HTMLElement>;
        onAbortCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlay?: react.ReactEventHandler<HTMLElement>;
        onCanPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThrough?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThroughCapture?: react.ReactEventHandler<HTMLElement>;
        onDurationChange?: react.ReactEventHandler<HTMLElement>;
        onDurationChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onEmptied?: react.ReactEventHandler<HTMLElement>;
        onEmptiedCapture?: react.ReactEventHandler<HTMLElement>;
        onEncrypted?: react.ReactEventHandler<HTMLElement>;
        onEncryptedCapture?: react.ReactEventHandler<HTMLElement>;
        onEnded?: react.ReactEventHandler<HTMLElement>;
        onEndedCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedData?: react.ReactEventHandler<HTMLElement>;
        onLoadedDataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadata?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadStart?: react.ReactEventHandler<HTMLElement>;
        onLoadStartCapture?: react.ReactEventHandler<HTMLElement>;
        onPause?: react.ReactEventHandler<HTMLElement>;
        onPauseCapture?: react.ReactEventHandler<HTMLElement>;
        onPlay?: react.ReactEventHandler<HTMLElement>;
        onPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onPlaying?: react.ReactEventHandler<HTMLElement>;
        onPlayingCapture?: react.ReactEventHandler<HTMLElement>;
        onProgress?: react.ReactEventHandler<HTMLElement>;
        onProgressCapture?: react.ReactEventHandler<HTMLElement>;
        onRateChange?: react.ReactEventHandler<HTMLElement>;
        onRateChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeked?: react.ReactEventHandler<HTMLElement>;
        onSeekedCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeking?: react.ReactEventHandler<HTMLElement>;
        onSeekingCapture?: react.ReactEventHandler<HTMLElement>;
        onStalled?: react.ReactEventHandler<HTMLElement>;
        onStalledCapture?: react.ReactEventHandler<HTMLElement>;
        onSuspend?: react.ReactEventHandler<HTMLElement>;
        onSuspendCapture?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdate?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdateCapture?: react.ReactEventHandler<HTMLElement>;
        onVolumeChange?: react.ReactEventHandler<HTMLElement>;
        onVolumeChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onWaiting?: react.ReactEventHandler<HTMLElement>;
        onWaitingCapture?: react.ReactEventHandler<HTMLElement>;
        onAuxClick?: react.MouseEventHandler<HTMLElement>;
        onAuxClickCapture?: react.MouseEventHandler<HTMLElement>;
        onClick?: react.MouseEventHandler<HTMLElement>;
        onClickCapture?: react.MouseEventHandler<HTMLElement>;
        onContextMenu?: react.MouseEventHandler<HTMLElement>;
        onContextMenuCapture?: react.MouseEventHandler<HTMLElement>;
        onDoubleClick?: react.MouseEventHandler<HTMLElement>;
        onDoubleClickCapture?: react.MouseEventHandler<HTMLElement>;
        onDrag?: react.DragEventHandler<HTMLElement>;
        onDragCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnd?: react.DragEventHandler<HTMLElement>;
        onDragEndCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnter?: react.DragEventHandler<HTMLElement>;
        onDragEnterCapture?: react.DragEventHandler<HTMLElement>;
        onDragExit?: react.DragEventHandler<HTMLElement>;
        onDragExitCapture?: react.DragEventHandler<HTMLElement>;
        onDragLeave?: react.DragEventHandler<HTMLElement>;
        onDragLeaveCapture?: react.DragEventHandler<HTMLElement>;
        onDragOver?: react.DragEventHandler<HTMLElement>;
        onDragOverCapture?: react.DragEventHandler<HTMLElement>;
        onDragStart?: react.DragEventHandler<HTMLElement>;
        onDragStartCapture?: react.DragEventHandler<HTMLElement>;
        onDrop?: react.DragEventHandler<HTMLElement>;
        onDropCapture?: react.DragEventHandler<HTMLElement>;
        onMouseDown?: react.MouseEventHandler<HTMLElement>;
        onMouseDownCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseEnter?: react.MouseEventHandler<HTMLElement>;
        onMouseLeave?: react.MouseEventHandler<HTMLElement>;
        onMouseMove?: react.MouseEventHandler<HTMLElement>;
        onMouseMoveCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOut?: react.MouseEventHandler<HTMLElement>;
        onMouseOutCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOver?: react.MouseEventHandler<HTMLElement>;
        onMouseOverCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseUp?: react.MouseEventHandler<HTMLElement>;
        onMouseUpCapture?: react.MouseEventHandler<HTMLElement>;
        onSelect?: react.ReactEventHandler<HTMLElement>;
        onSelectCapture?: react.ReactEventHandler<HTMLElement>;
        onTouchCancel?: react.TouchEventHandler<HTMLElement>;
        onTouchCancelCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchEnd?: react.TouchEventHandler<HTMLElement>;
        onTouchEndCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchMove?: react.TouchEventHandler<HTMLElement>;
        onTouchMoveCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchStart?: react.TouchEventHandler<HTMLElement>;
        onTouchStartCapture?: react.TouchEventHandler<HTMLElement>;
        onPointerDown?: react.PointerEventHandler<HTMLElement>;
        onPointerDownCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerMove?: react.PointerEventHandler<HTMLElement>;
        onPointerMoveCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerUp?: react.PointerEventHandler<HTMLElement>;
        onPointerUpCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerCancel?: react.PointerEventHandler<HTMLElement>;
        onPointerCancelCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerEnter?: react.PointerEventHandler<HTMLElement>;
        onPointerLeave?: react.PointerEventHandler<HTMLElement>;
        onPointerOver?: react.PointerEventHandler<HTMLElement>;
        onPointerOverCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerOut?: react.PointerEventHandler<HTMLElement>;
        onPointerOutCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onScroll?: react.UIEventHandler<HTMLElement>;
        onScrollCapture?: react.UIEventHandler<HTMLElement>;
        onWheel?: react.WheelEventHandler<HTMLElement>;
        onWheelCapture?: react.WheelEventHandler<HTMLElement>;
        onAnimationStart?: react.AnimationEventHandler<HTMLElement>;
        onAnimationStartCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEnd?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEndCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIteration?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIterationCapture?: react.AnimationEventHandler<HTMLElement>;
        onTransitionEnd?: react.TransitionEventHandler<HTMLElement>;
        onTransitionEndCapture?: react.TransitionEventHandler<HTMLElement>;
    };
    getImageProps: ({ src, onLoad, onError, }: {
        src?: string;
        onLoad?: (e: React.SyntheticEvent<HTMLImageElement>) => void;
        onError?: (e: React.SyntheticEvent<HTMLImageElement>) => void;
    }) => {
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: react.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: react.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        exportparts?: string | undefined;
        part?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        children?: react.ReactNode | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: react.ClipboardEventHandler<HTMLImageElement>;
        onCopyCapture?: react.ClipboardEventHandler<HTMLImageElement>;
        onCut?: react.ClipboardEventHandler<HTMLImageElement>;
        onCutCapture?: react.ClipboardEventHandler<HTMLImageElement>;
        onPaste?: react.ClipboardEventHandler<HTMLImageElement>;
        onPasteCapture?: react.ClipboardEventHandler<HTMLImageElement>;
        onCompositionEnd?: react.CompositionEventHandler<HTMLImageElement>;
        onCompositionEndCapture?: react.CompositionEventHandler<HTMLImageElement>;
        onCompositionStart?: react.CompositionEventHandler<HTMLImageElement>;
        onCompositionStartCapture?: react.CompositionEventHandler<HTMLImageElement>;
        onCompositionUpdate?: react.CompositionEventHandler<HTMLImageElement>;
        onCompositionUpdateCapture?: react.CompositionEventHandler<HTMLImageElement>;
        onFocus?: react.FocusEventHandler<HTMLImageElement>;
        onFocusCapture?: react.FocusEventHandler<HTMLImageElement>;
        onBlur?: react.FocusEventHandler<HTMLImageElement>;
        onBlurCapture?: react.FocusEventHandler<HTMLImageElement>;
        onChange?: react.FormEventHandler<HTMLImageElement>;
        onChangeCapture?: react.FormEventHandler<HTMLImageElement>;
        onBeforeInput?: react.InputEventHandler<HTMLImageElement>;
        onBeforeInputCapture?: react.FormEventHandler<HTMLImageElement>;
        onInput?: react.FormEventHandler<HTMLImageElement>;
        onInputCapture?: react.FormEventHandler<HTMLImageElement>;
        onReset?: react.FormEventHandler<HTMLImageElement>;
        onResetCapture?: react.FormEventHandler<HTMLImageElement>;
        onSubmit?: react.FormEventHandler<HTMLImageElement>;
        onSubmitCapture?: react.FormEventHandler<HTMLImageElement>;
        onInvalid?: react.FormEventHandler<HTMLImageElement>;
        onInvalidCapture?: react.FormEventHandler<HTMLImageElement>;
        onLoad?: react.ReactEventHandler<HTMLImageElement>;
        onLoadCapture?: react.ReactEventHandler<HTMLImageElement>;
        onError?: react.ReactEventHandler<HTMLImageElement>;
        onErrorCapture?: react.ReactEventHandler<HTMLImageElement>;
        onKeyDown?: react.KeyboardEventHandler<HTMLImageElement>;
        onKeyDownCapture?: react.KeyboardEventHandler<HTMLImageElement>;
        onKeyPress?: react.KeyboardEventHandler<HTMLImageElement>;
        onKeyPressCapture?: react.KeyboardEventHandler<HTMLImageElement>;
        onKeyUp?: react.KeyboardEventHandler<HTMLImageElement>;
        onKeyUpCapture?: react.KeyboardEventHandler<HTMLImageElement>;
        onAbort?: react.ReactEventHandler<HTMLImageElement>;
        onAbortCapture?: react.ReactEventHandler<HTMLImageElement>;
        onCanPlay?: react.ReactEventHandler<HTMLImageElement>;
        onCanPlayCapture?: react.ReactEventHandler<HTMLImageElement>;
        onCanPlayThrough?: react.ReactEventHandler<HTMLImageElement>;
        onCanPlayThroughCapture?: react.ReactEventHandler<HTMLImageElement>;
        onDurationChange?: react.ReactEventHandler<HTMLImageElement>;
        onDurationChangeCapture?: react.ReactEventHandler<HTMLImageElement>;
        onEmptied?: react.ReactEventHandler<HTMLImageElement>;
        onEmptiedCapture?: react.ReactEventHandler<HTMLImageElement>;
        onEncrypted?: react.ReactEventHandler<HTMLImageElement>;
        onEncryptedCapture?: react.ReactEventHandler<HTMLImageElement>;
        onEnded?: react.ReactEventHandler<HTMLImageElement>;
        onEndedCapture?: react.ReactEventHandler<HTMLImageElement>;
        onLoadedData?: react.ReactEventHandler<HTMLImageElement>;
        onLoadedDataCapture?: react.ReactEventHandler<HTMLImageElement>;
        onLoadedMetadata?: react.ReactEventHandler<HTMLImageElement>;
        onLoadedMetadataCapture?: react.ReactEventHandler<HTMLImageElement>;
        onLoadStart?: react.ReactEventHandler<HTMLImageElement>;
        onLoadStartCapture?: react.ReactEventHandler<HTMLImageElement>;
        onPause?: react.ReactEventHandler<HTMLImageElement>;
        onPauseCapture?: react.ReactEventHandler<HTMLImageElement>;
        onPlay?: react.ReactEventHandler<HTMLImageElement>;
        onPlayCapture?: react.ReactEventHandler<HTMLImageElement>;
        onPlaying?: react.ReactEventHandler<HTMLImageElement>;
        onPlayingCapture?: react.ReactEventHandler<HTMLImageElement>;
        onProgress?: react.ReactEventHandler<HTMLImageElement>;
        onProgressCapture?: react.ReactEventHandler<HTMLImageElement>;
        onRateChange?: react.ReactEventHandler<HTMLImageElement>;
        onRateChangeCapture?: react.ReactEventHandler<HTMLImageElement>;
        onSeeked?: react.ReactEventHandler<HTMLImageElement>;
        onSeekedCapture?: react.ReactEventHandler<HTMLImageElement>;
        onSeeking?: react.ReactEventHandler<HTMLImageElement>;
        onSeekingCapture?: react.ReactEventHandler<HTMLImageElement>;
        onStalled?: react.ReactEventHandler<HTMLImageElement>;
        onStalledCapture?: react.ReactEventHandler<HTMLImageElement>;
        onSuspend?: react.ReactEventHandler<HTMLImageElement>;
        onSuspendCapture?: react.ReactEventHandler<HTMLImageElement>;
        onTimeUpdate?: react.ReactEventHandler<HTMLImageElement>;
        onTimeUpdateCapture?: react.ReactEventHandler<HTMLImageElement>;
        onVolumeChange?: react.ReactEventHandler<HTMLImageElement>;
        onVolumeChangeCapture?: react.ReactEventHandler<HTMLImageElement>;
        onWaiting?: react.ReactEventHandler<HTMLImageElement>;
        onWaitingCapture?: react.ReactEventHandler<HTMLImageElement>;
        onAuxClick?: react.MouseEventHandler<HTMLImageElement>;
        onAuxClickCapture?: react.MouseEventHandler<HTMLImageElement>;
        onClick?: react.MouseEventHandler<HTMLImageElement>;
        onClickCapture?: react.MouseEventHandler<HTMLImageElement>;
        onContextMenu?: react.MouseEventHandler<HTMLImageElement>;
        onContextMenuCapture?: react.MouseEventHandler<HTMLImageElement>;
        onDoubleClick?: react.MouseEventHandler<HTMLImageElement>;
        onDoubleClickCapture?: react.MouseEventHandler<HTMLImageElement>;
        onDrag?: react.DragEventHandler<HTMLImageElement>;
        onDragCapture?: react.DragEventHandler<HTMLImageElement>;
        onDragEnd?: react.DragEventHandler<HTMLImageElement>;
        onDragEndCapture?: react.DragEventHandler<HTMLImageElement>;
        onDragEnter?: react.DragEventHandler<HTMLImageElement>;
        onDragEnterCapture?: react.DragEventHandler<HTMLImageElement>;
        onDragExit?: react.DragEventHandler<HTMLImageElement>;
        onDragExitCapture?: react.DragEventHandler<HTMLImageElement>;
        onDragLeave?: react.DragEventHandler<HTMLImageElement>;
        onDragLeaveCapture?: react.DragEventHandler<HTMLImageElement>;
        onDragOver?: react.DragEventHandler<HTMLImageElement>;
        onDragOverCapture?: react.DragEventHandler<HTMLImageElement>;
        onDragStart?: react.DragEventHandler<HTMLImageElement>;
        onDragStartCapture?: react.DragEventHandler<HTMLImageElement>;
        onDrop?: react.DragEventHandler<HTMLImageElement>;
        onDropCapture?: react.DragEventHandler<HTMLImageElement>;
        onMouseDown?: react.MouseEventHandler<HTMLImageElement>;
        onMouseDownCapture?: react.MouseEventHandler<HTMLImageElement>;
        onMouseEnter?: react.MouseEventHandler<HTMLImageElement>;
        onMouseLeave?: react.MouseEventHandler<HTMLImageElement>;
        onMouseMove?: react.MouseEventHandler<HTMLImageElement>;
        onMouseMoveCapture?: react.MouseEventHandler<HTMLImageElement>;
        onMouseOut?: react.MouseEventHandler<HTMLImageElement>;
        onMouseOutCapture?: react.MouseEventHandler<HTMLImageElement>;
        onMouseOver?: react.MouseEventHandler<HTMLImageElement>;
        onMouseOverCapture?: react.MouseEventHandler<HTMLImageElement>;
        onMouseUp?: react.MouseEventHandler<HTMLImageElement>;
        onMouseUpCapture?: react.MouseEventHandler<HTMLImageElement>;
        onSelect?: react.ReactEventHandler<HTMLImageElement>;
        onSelectCapture?: react.ReactEventHandler<HTMLImageElement>;
        onTouchCancel?: react.TouchEventHandler<HTMLImageElement>;
        onTouchCancelCapture?: react.TouchEventHandler<HTMLImageElement>;
        onTouchEnd?: react.TouchEventHandler<HTMLImageElement>;
        onTouchEndCapture?: react.TouchEventHandler<HTMLImageElement>;
        onTouchMove?: react.TouchEventHandler<HTMLImageElement>;
        onTouchMoveCapture?: react.TouchEventHandler<HTMLImageElement>;
        onTouchStart?: react.TouchEventHandler<HTMLImageElement>;
        onTouchStartCapture?: react.TouchEventHandler<HTMLImageElement>;
        onPointerDown?: react.PointerEventHandler<HTMLImageElement>;
        onPointerDownCapture?: react.PointerEventHandler<HTMLImageElement>;
        onPointerMove?: react.PointerEventHandler<HTMLImageElement>;
        onPointerMoveCapture?: react.PointerEventHandler<HTMLImageElement>;
        onPointerUp?: react.PointerEventHandler<HTMLImageElement>;
        onPointerUpCapture?: react.PointerEventHandler<HTMLImageElement>;
        onPointerCancel?: react.PointerEventHandler<HTMLImageElement>;
        onPointerCancelCapture?: react.PointerEventHandler<HTMLImageElement>;
        onPointerEnter?: react.PointerEventHandler<HTMLImageElement>;
        onPointerLeave?: react.PointerEventHandler<HTMLImageElement>;
        onPointerOver?: react.PointerEventHandler<HTMLImageElement>;
        onPointerOverCapture?: react.PointerEventHandler<HTMLImageElement>;
        onPointerOut?: react.PointerEventHandler<HTMLImageElement>;
        onPointerOutCapture?: react.PointerEventHandler<HTMLImageElement>;
        onGotPointerCapture?: react.PointerEventHandler<HTMLImageElement>;
        onGotPointerCaptureCapture?: react.PointerEventHandler<HTMLImageElement>;
        onLostPointerCapture?: react.PointerEventHandler<HTMLImageElement>;
        onLostPointerCaptureCapture?: react.PointerEventHandler<HTMLImageElement>;
        onScroll?: react.UIEventHandler<HTMLImageElement>;
        onScrollCapture?: react.UIEventHandler<HTMLImageElement>;
        onWheel?: react.WheelEventHandler<HTMLImageElement>;
        onWheelCapture?: react.WheelEventHandler<HTMLImageElement>;
        onAnimationStart?: react.AnimationEventHandler<HTMLImageElement>;
        onAnimationStartCapture?: react.AnimationEventHandler<HTMLImageElement>;
        onAnimationEnd?: react.AnimationEventHandler<HTMLImageElement>;
        onAnimationEndCapture?: react.AnimationEventHandler<HTMLImageElement>;
        onAnimationIteration?: react.AnimationEventHandler<HTMLImageElement>;
        onAnimationIterationCapture?: react.AnimationEventHandler<HTMLImageElement>;
        onTransitionEnd?: react.TransitionEventHandler<HTMLImageElement>;
        onTransitionEndCapture?: react.TransitionEventHandler<HTMLImageElement>;
        alt?: string | undefined;
        crossOrigin?: "" | "anonymous" | "use-credentials";
        decoding?: "async" | "auto" | "sync" | undefined;
        fetchPriority?: "high" | "low" | "auto";
        height?: number | string | undefined;
        loading?: "eager" | "lazy" | undefined;
        referrerPolicy?: react.HTMLAttributeReferrerPolicy | undefined;
        sizes?: string | undefined;
        src?: string | undefined;
        srcSet?: string | undefined;
        useMap?: string | undefined;
        width?: number | string | undefined;
    };
    fallbackProps: {
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: react.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: react.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        exportparts?: string | undefined;
        part?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        children?: react.ReactNode | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: react.ClipboardEventHandler<HTMLElement>;
        onCopyCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCut?: react.ClipboardEventHandler<HTMLElement>;
        onCutCapture?: react.ClipboardEventHandler<HTMLElement>;
        onPaste?: react.ClipboardEventHandler<HTMLElement>;
        onPasteCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCompositionEnd?: react.CompositionEventHandler<HTMLElement>;
        onCompositionEndCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStart?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStartCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdate?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdateCapture?: react.CompositionEventHandler<HTMLElement>;
        onFocus?: react.FocusEventHandler<HTMLElement>;
        onFocusCapture?: react.FocusEventHandler<HTMLElement>;
        onBlur?: react.FocusEventHandler<HTMLElement>;
        onBlurCapture?: react.FocusEventHandler<HTMLElement>;
        onChange?: react.FormEventHandler<HTMLElement>;
        onChangeCapture?: react.FormEventHandler<HTMLElement>;
        onBeforeInput?: react.InputEventHandler<HTMLElement>;
        onBeforeInputCapture?: react.FormEventHandler<HTMLElement>;
        onInput?: react.FormEventHandler<HTMLElement>;
        onInputCapture?: react.FormEventHandler<HTMLElement>;
        onReset?: react.FormEventHandler<HTMLElement>;
        onResetCapture?: react.FormEventHandler<HTMLElement>;
        onSubmit?: react.FormEventHandler<HTMLElement>;
        onSubmitCapture?: react.FormEventHandler<HTMLElement>;
        onInvalid?: react.FormEventHandler<HTMLElement>;
        onInvalidCapture?: react.FormEventHandler<HTMLElement>;
        onLoad?: react.ReactEventHandler<HTMLElement>;
        onLoadCapture?: react.ReactEventHandler<HTMLElement>;
        onError?: react.ReactEventHandler<HTMLElement>;
        onErrorCapture?: react.ReactEventHandler<HTMLElement>;
        onKeyDown?: react.KeyboardEventHandler<HTMLElement>;
        onKeyDownCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPress?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPressCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUp?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUpCapture?: react.KeyboardEventHandler<HTMLElement>;
        onAbort?: react.ReactEventHandler<HTMLElement>;
        onAbortCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlay?: react.ReactEventHandler<HTMLElement>;
        onCanPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThrough?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThroughCapture?: react.ReactEventHandler<HTMLElement>;
        onDurationChange?: react.ReactEventHandler<HTMLElement>;
        onDurationChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onEmptied?: react.ReactEventHandler<HTMLElement>;
        onEmptiedCapture?: react.ReactEventHandler<HTMLElement>;
        onEncrypted?: react.ReactEventHandler<HTMLElement>;
        onEncryptedCapture?: react.ReactEventHandler<HTMLElement>;
        onEnded?: react.ReactEventHandler<HTMLElement>;
        onEndedCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedData?: react.ReactEventHandler<HTMLElement>;
        onLoadedDataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadata?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadStart?: react.ReactEventHandler<HTMLElement>;
        onLoadStartCapture?: react.ReactEventHandler<HTMLElement>;
        onPause?: react.ReactEventHandler<HTMLElement>;
        onPauseCapture?: react.ReactEventHandler<HTMLElement>;
        onPlay?: react.ReactEventHandler<HTMLElement>;
        onPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onPlaying?: react.ReactEventHandler<HTMLElement>;
        onPlayingCapture?: react.ReactEventHandler<HTMLElement>;
        onProgress?: react.ReactEventHandler<HTMLElement>;
        onProgressCapture?: react.ReactEventHandler<HTMLElement>;
        onRateChange?: react.ReactEventHandler<HTMLElement>;
        onRateChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeked?: react.ReactEventHandler<HTMLElement>;
        onSeekedCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeking?: react.ReactEventHandler<HTMLElement>;
        onSeekingCapture?: react.ReactEventHandler<HTMLElement>;
        onStalled?: react.ReactEventHandler<HTMLElement>;
        onStalledCapture?: react.ReactEventHandler<HTMLElement>;
        onSuspend?: react.ReactEventHandler<HTMLElement>;
        onSuspendCapture?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdate?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdateCapture?: react.ReactEventHandler<HTMLElement>;
        onVolumeChange?: react.ReactEventHandler<HTMLElement>;
        onVolumeChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onWaiting?: react.ReactEventHandler<HTMLElement>;
        onWaitingCapture?: react.ReactEventHandler<HTMLElement>;
        onAuxClick?: react.MouseEventHandler<HTMLElement>;
        onAuxClickCapture?: react.MouseEventHandler<HTMLElement>;
        onClick?: react.MouseEventHandler<HTMLElement>;
        onClickCapture?: react.MouseEventHandler<HTMLElement>;
        onContextMenu?: react.MouseEventHandler<HTMLElement>;
        onContextMenuCapture?: react.MouseEventHandler<HTMLElement>;
        onDoubleClick?: react.MouseEventHandler<HTMLElement>;
        onDoubleClickCapture?: react.MouseEventHandler<HTMLElement>;
        onDrag?: react.DragEventHandler<HTMLElement>;
        onDragCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnd?: react.DragEventHandler<HTMLElement>;
        onDragEndCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnter?: react.DragEventHandler<HTMLElement>;
        onDragEnterCapture?: react.DragEventHandler<HTMLElement>;
        onDragExit?: react.DragEventHandler<HTMLElement>;
        onDragExitCapture?: react.DragEventHandler<HTMLElement>;
        onDragLeave?: react.DragEventHandler<HTMLElement>;
        onDragLeaveCapture?: react.DragEventHandler<HTMLElement>;
        onDragOver?: react.DragEventHandler<HTMLElement>;
        onDragOverCapture?: react.DragEventHandler<HTMLElement>;
        onDragStart?: react.DragEventHandler<HTMLElement>;
        onDragStartCapture?: react.DragEventHandler<HTMLElement>;
        onDrop?: react.DragEventHandler<HTMLElement>;
        onDropCapture?: react.DragEventHandler<HTMLElement>;
        onMouseDown?: react.MouseEventHandler<HTMLElement>;
        onMouseDownCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseEnter?: react.MouseEventHandler<HTMLElement>;
        onMouseLeave?: react.MouseEventHandler<HTMLElement>;
        onMouseMove?: react.MouseEventHandler<HTMLElement>;
        onMouseMoveCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOut?: react.MouseEventHandler<HTMLElement>;
        onMouseOutCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOver?: react.MouseEventHandler<HTMLElement>;
        onMouseOverCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseUp?: react.MouseEventHandler<HTMLElement>;
        onMouseUpCapture?: react.MouseEventHandler<HTMLElement>;
        onSelect?: react.ReactEventHandler<HTMLElement>;
        onSelectCapture?: react.ReactEventHandler<HTMLElement>;
        onTouchCancel?: react.TouchEventHandler<HTMLElement>;
        onTouchCancelCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchEnd?: react.TouchEventHandler<HTMLElement>;
        onTouchEndCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchMove?: react.TouchEventHandler<HTMLElement>;
        onTouchMoveCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchStart?: react.TouchEventHandler<HTMLElement>;
        onTouchStartCapture?: react.TouchEventHandler<HTMLElement>;
        onPointerDown?: react.PointerEventHandler<HTMLElement>;
        onPointerDownCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerMove?: react.PointerEventHandler<HTMLElement>;
        onPointerMoveCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerUp?: react.PointerEventHandler<HTMLElement>;
        onPointerUpCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerCancel?: react.PointerEventHandler<HTMLElement>;
        onPointerCancelCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerEnter?: react.PointerEventHandler<HTMLElement>;
        onPointerLeave?: react.PointerEventHandler<HTMLElement>;
        onPointerOver?: react.PointerEventHandler<HTMLElement>;
        onPointerOverCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerOut?: react.PointerEventHandler<HTMLElement>;
        onPointerOutCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onScroll?: react.UIEventHandler<HTMLElement>;
        onScrollCapture?: react.UIEventHandler<HTMLElement>;
        onWheel?: react.WheelEventHandler<HTMLElement>;
        onWheelCapture?: react.WheelEventHandler<HTMLElement>;
        onAnimationStart?: react.AnimationEventHandler<HTMLElement>;
        onAnimationStartCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEnd?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEndCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIteration?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIterationCapture?: react.AnimationEventHandler<HTMLElement>;
        onTransitionEnd?: react.TransitionEventHandler<HTMLElement>;
        onTransitionEndCapture?: react.TransitionEventHandler<HTMLElement>;
    };
};

interface AvatarRootProps extends UseAvatarProps, PrimitiveProps, react.HTMLAttributes<HTMLDivElement> {
}
declare const AvatarRoot: react.ForwardRefExoticComponent<AvatarRootProps & react.RefAttributes<HTMLDivElement>>;
interface AvatarImageProps extends PrimitiveProps, react.ImgHTMLAttributes<HTMLImageElement> {
}
declare const AvatarImage: react.ForwardRefExoticComponent<AvatarImageProps & react.RefAttributes<HTMLImageElement>>;
interface AvatarFallbackProps extends PrimitiveProps, react.HTMLAttributes<HTMLDivElement> {
}
declare const AvatarFallback: react.ForwardRefExoticComponent<AvatarFallbackProps & react.RefAttributes<HTMLDivElement>>;

interface UseAvatarContext extends UseAvatarReturn {
}
declare function useAvatarContext<T extends boolean | undefined = true>({ strict, }?: {
    strict?: T;
}): T extends false ? UseAvatarContext | null : UseAvatarContext;

declare namespace Avatar_namespace {
  export { AvatarFallback as Fallback, AvatarImage as Image, AvatarRoot as Root };
  export type { AvatarFallbackProps as FallbackProps, AvatarImageProps as ImageProps, AvatarRootProps as RootProps };
}

export { Avatar_namespace as Avatar, AvatarFallback, AvatarImage, AvatarRoot, useAvatarContext };
export type { AvatarFallbackProps, AvatarImageProps, AvatarRootProps, UseAvatarContext };
