import * as react_jsx_runtime from 'react/jsx-runtime';
import * as react from 'react';
import { PrimitiveProps } from '@grape-design/react-primitive';

interface UsePullToRefreshStateProps {
    /**
     * The threshold value to trigger the refresh. (px)
     * @default 44
     */
    threshold?: number;
    /**
     * The multiplier to calculate displacement from the touch movement.
     * @default 0.5
     */
    displacementMultiplier?: number;
    /**
     * Callback when the pull-to-refresh has started to pull.
     */
    onPtrPullStart?: (ctx: PullToRefreshContext) => void;
    /**
     * Callback when the pull-to-refresh is moving during the pull.
     */
    onPtrPullMove?: (ctx: PullToRefreshContext) => void;
    /**
     * Callback when the pull-to-refresh is released.
     * It does not matter if it is ready or not. If you want to handle the refresh, use `onPtrRefresh`.
     */
    onPtrPullEnd?: (ctx: PullToRefreshContext) => void;
    /**
     * Callback when the pull-to-refresh is pulled over the threshold.
     */
    onPtrReady?: () => void;
    /**
     * Callback when the pull-to-refresh is released after ready.
     */
    onPtrRefresh?: () => Promise<void>;
    /**
     * Whether to disable the pull-to-refresh.
     * @default false
     */
    disabled?: boolean;
}
interface PullToRefreshContext {
    y0: number;
    y: number;
    displacement: number;
    displacementRatio: number;
}
type PullToRefreshState = "idle" | "pulling" | "ready" | "loading";
interface UsePullToRefreshProps extends UsePullToRefreshStateProps {
}
interface PullToRefreshIndicatorRenderProps {
    minValue: number;
    maxValue: number;
    value: number | undefined;
}
type UsePullToRefreshReturn = ReturnType<typeof usePullToRefresh>;
declare function usePullToRefresh(props: UsePullToRefreshProps): {
    state: PullToRefreshState;
    refs: {
        root: react.MutableRefObject<HTMLDivElement>;
    };
    stateProps: {
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: react.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: react.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        exportparts?: string | undefined;
        part?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        children?: react.ReactNode | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: react.ClipboardEventHandler<HTMLElement>;
        onCopyCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCut?: react.ClipboardEventHandler<HTMLElement>;
        onCutCapture?: react.ClipboardEventHandler<HTMLElement>;
        onPaste?: react.ClipboardEventHandler<HTMLElement>;
        onPasteCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCompositionEnd?: react.CompositionEventHandler<HTMLElement>;
        onCompositionEndCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStart?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStartCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdate?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdateCapture?: react.CompositionEventHandler<HTMLElement>;
        onFocus?: react.FocusEventHandler<HTMLElement>;
        onFocusCapture?: react.FocusEventHandler<HTMLElement>;
        onBlur?: react.FocusEventHandler<HTMLElement>;
        onBlurCapture?: react.FocusEventHandler<HTMLElement>;
        onChange?: react.FormEventHandler<HTMLElement>;
        onChangeCapture?: react.FormEventHandler<HTMLElement>;
        onBeforeInput?: react.InputEventHandler<HTMLElement>;
        onBeforeInputCapture?: react.FormEventHandler<HTMLElement>;
        onInput?: react.FormEventHandler<HTMLElement>;
        onInputCapture?: react.FormEventHandler<HTMLElement>;
        onReset?: react.FormEventHandler<HTMLElement>;
        onResetCapture?: react.FormEventHandler<HTMLElement>;
        onSubmit?: react.FormEventHandler<HTMLElement>;
        onSubmitCapture?: react.FormEventHandler<HTMLElement>;
        onInvalid?: react.FormEventHandler<HTMLElement>;
        onInvalidCapture?: react.FormEventHandler<HTMLElement>;
        onLoad?: react.ReactEventHandler<HTMLElement>;
        onLoadCapture?: react.ReactEventHandler<HTMLElement>;
        onError?: react.ReactEventHandler<HTMLElement>;
        onErrorCapture?: react.ReactEventHandler<HTMLElement>;
        onKeyDown?: react.KeyboardEventHandler<HTMLElement>;
        onKeyDownCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPress?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPressCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUp?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUpCapture?: react.KeyboardEventHandler<HTMLElement>;
        onAbort?: react.ReactEventHandler<HTMLElement>;
        onAbortCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlay?: react.ReactEventHandler<HTMLElement>;
        onCanPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThrough?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThroughCapture?: react.ReactEventHandler<HTMLElement>;
        onDurationChange?: react.ReactEventHandler<HTMLElement>;
        onDurationChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onEmptied?: react.ReactEventHandler<HTMLElement>;
        onEmptiedCapture?: react.ReactEventHandler<HTMLElement>;
        onEncrypted?: react.ReactEventHandler<HTMLElement>;
        onEncryptedCapture?: react.ReactEventHandler<HTMLElement>;
        onEnded?: react.ReactEventHandler<HTMLElement>;
        onEndedCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedData?: react.ReactEventHandler<HTMLElement>;
        onLoadedDataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadata?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadStart?: react.ReactEventHandler<HTMLElement>;
        onLoadStartCapture?: react.ReactEventHandler<HTMLElement>;
        onPause?: react.ReactEventHandler<HTMLElement>;
        onPauseCapture?: react.ReactEventHandler<HTMLElement>;
        onPlay?: react.ReactEventHandler<HTMLElement>;
        onPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onPlaying?: react.ReactEventHandler<HTMLElement>;
        onPlayingCapture?: react.ReactEventHandler<HTMLElement>;
        onProgress?: react.ReactEventHandler<HTMLElement>;
        onProgressCapture?: react.ReactEventHandler<HTMLElement>;
        onRateChange?: react.ReactEventHandler<HTMLElement>;
        onRateChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeked?: react.ReactEventHandler<HTMLElement>;
        onSeekedCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeking?: react.ReactEventHandler<HTMLElement>;
        onSeekingCapture?: react.ReactEventHandler<HTMLElement>;
        onStalled?: react.ReactEventHandler<HTMLElement>;
        onStalledCapture?: react.ReactEventHandler<HTMLElement>;
        onSuspend?: react.ReactEventHandler<HTMLElement>;
        onSuspendCapture?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdate?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdateCapture?: react.ReactEventHandler<HTMLElement>;
        onVolumeChange?: react.ReactEventHandler<HTMLElement>;
        onVolumeChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onWaiting?: react.ReactEventHandler<HTMLElement>;
        onWaitingCapture?: react.ReactEventHandler<HTMLElement>;
        onAuxClick?: react.MouseEventHandler<HTMLElement>;
        onAuxClickCapture?: react.MouseEventHandler<HTMLElement>;
        onClick?: react.MouseEventHandler<HTMLElement>;
        onClickCapture?: react.MouseEventHandler<HTMLElement>;
        onContextMenu?: react.MouseEventHandler<HTMLElement>;
        onContextMenuCapture?: react.MouseEventHandler<HTMLElement>;
        onDoubleClick?: react.MouseEventHandler<HTMLElement>;
        onDoubleClickCapture?: react.MouseEventHandler<HTMLElement>;
        onDrag?: react.DragEventHandler<HTMLElement>;
        onDragCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnd?: react.DragEventHandler<HTMLElement>;
        onDragEndCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnter?: react.DragEventHandler<HTMLElement>;
        onDragEnterCapture?: react.DragEventHandler<HTMLElement>;
        onDragExit?: react.DragEventHandler<HTMLElement>;
        onDragExitCapture?: react.DragEventHandler<HTMLElement>;
        onDragLeave?: react.DragEventHandler<HTMLElement>;
        onDragLeaveCapture?: react.DragEventHandler<HTMLElement>;
        onDragOver?: react.DragEventHandler<HTMLElement>;
        onDragOverCapture?: react.DragEventHandler<HTMLElement>;
        onDragStart?: react.DragEventHandler<HTMLElement>;
        onDragStartCapture?: react.DragEventHandler<HTMLElement>;
        onDrop?: react.DragEventHandler<HTMLElement>;
        onDropCapture?: react.DragEventHandler<HTMLElement>;
        onMouseDown?: react.MouseEventHandler<HTMLElement>;
        onMouseDownCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseEnter?: react.MouseEventHandler<HTMLElement>;
        onMouseLeave?: react.MouseEventHandler<HTMLElement>;
        onMouseMove?: react.MouseEventHandler<HTMLElement>;
        onMouseMoveCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOut?: react.MouseEventHandler<HTMLElement>;
        onMouseOutCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOver?: react.MouseEventHandler<HTMLElement>;
        onMouseOverCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseUp?: react.MouseEventHandler<HTMLElement>;
        onMouseUpCapture?: react.MouseEventHandler<HTMLElement>;
        onSelect?: react.ReactEventHandler<HTMLElement>;
        onSelectCapture?: react.ReactEventHandler<HTMLElement>;
        onTouchCancel?: react.TouchEventHandler<HTMLElement>;
        onTouchCancelCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchEnd?: react.TouchEventHandler<HTMLElement>;
        onTouchEndCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchMove?: react.TouchEventHandler<HTMLElement>;
        onTouchMoveCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchStart?: react.TouchEventHandler<HTMLElement>;
        onTouchStartCapture?: react.TouchEventHandler<HTMLElement>;
        onPointerDown?: react.PointerEventHandler<HTMLElement>;
        onPointerDownCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerMove?: react.PointerEventHandler<HTMLElement>;
        onPointerMoveCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerUp?: react.PointerEventHandler<HTMLElement>;
        onPointerUpCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerCancel?: react.PointerEventHandler<HTMLElement>;
        onPointerCancelCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerEnter?: react.PointerEventHandler<HTMLElement>;
        onPointerLeave?: react.PointerEventHandler<HTMLElement>;
        onPointerOver?: react.PointerEventHandler<HTMLElement>;
        onPointerOverCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerOut?: react.PointerEventHandler<HTMLElement>;
        onPointerOutCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onScroll?: react.UIEventHandler<HTMLElement>;
        onScrollCapture?: react.UIEventHandler<HTMLElement>;
        onWheel?: react.WheelEventHandler<HTMLElement>;
        onWheelCapture?: react.WheelEventHandler<HTMLElement>;
        onAnimationStart?: react.AnimationEventHandler<HTMLElement>;
        onAnimationStartCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEnd?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEndCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIteration?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIterationCapture?: react.AnimationEventHandler<HTMLElement>;
        onTransitionEnd?: react.TransitionEventHandler<HTMLElement>;
        onTransitionEndCapture?: react.TransitionEventHandler<HTMLElement>;
    };
    rootProps: {
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: react.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: react.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        exportparts?: string | undefined;
        part?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        children?: react.ReactNode | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: react.ClipboardEventHandler<HTMLElement>;
        onCopyCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCut?: react.ClipboardEventHandler<HTMLElement>;
        onCutCapture?: react.ClipboardEventHandler<HTMLElement>;
        onPaste?: react.ClipboardEventHandler<HTMLElement>;
        onPasteCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCompositionEnd?: react.CompositionEventHandler<HTMLElement>;
        onCompositionEndCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStart?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStartCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdate?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdateCapture?: react.CompositionEventHandler<HTMLElement>;
        onFocus?: react.FocusEventHandler<HTMLElement>;
        onFocusCapture?: react.FocusEventHandler<HTMLElement>;
        onBlur?: react.FocusEventHandler<HTMLElement>;
        onBlurCapture?: react.FocusEventHandler<HTMLElement>;
        onChange?: react.FormEventHandler<HTMLElement>;
        onChangeCapture?: react.FormEventHandler<HTMLElement>;
        onBeforeInput?: react.InputEventHandler<HTMLElement>;
        onBeforeInputCapture?: react.FormEventHandler<HTMLElement>;
        onInput?: react.FormEventHandler<HTMLElement>;
        onInputCapture?: react.FormEventHandler<HTMLElement>;
        onReset?: react.FormEventHandler<HTMLElement>;
        onResetCapture?: react.FormEventHandler<HTMLElement>;
        onSubmit?: react.FormEventHandler<HTMLElement>;
        onSubmitCapture?: react.FormEventHandler<HTMLElement>;
        onInvalid?: react.FormEventHandler<HTMLElement>;
        onInvalidCapture?: react.FormEventHandler<HTMLElement>;
        onLoad?: react.ReactEventHandler<HTMLElement>;
        onLoadCapture?: react.ReactEventHandler<HTMLElement>;
        onError?: react.ReactEventHandler<HTMLElement>;
        onErrorCapture?: react.ReactEventHandler<HTMLElement>;
        onKeyDown?: react.KeyboardEventHandler<HTMLElement>;
        onKeyDownCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPress?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPressCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUp?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUpCapture?: react.KeyboardEventHandler<HTMLElement>;
        onAbort?: react.ReactEventHandler<HTMLElement>;
        onAbortCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlay?: react.ReactEventHandler<HTMLElement>;
        onCanPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThrough?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThroughCapture?: react.ReactEventHandler<HTMLElement>;
        onDurationChange?: react.ReactEventHandler<HTMLElement>;
        onDurationChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onEmptied?: react.ReactEventHandler<HTMLElement>;
        onEmptiedCapture?: react.ReactEventHandler<HTMLElement>;
        onEncrypted?: react.ReactEventHandler<HTMLElement>;
        onEncryptedCapture?: react.ReactEventHandler<HTMLElement>;
        onEnded?: react.ReactEventHandler<HTMLElement>;
        onEndedCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedData?: react.ReactEventHandler<HTMLElement>;
        onLoadedDataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadata?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadStart?: react.ReactEventHandler<HTMLElement>;
        onLoadStartCapture?: react.ReactEventHandler<HTMLElement>;
        onPause?: react.ReactEventHandler<HTMLElement>;
        onPauseCapture?: react.ReactEventHandler<HTMLElement>;
        onPlay?: react.ReactEventHandler<HTMLElement>;
        onPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onPlaying?: react.ReactEventHandler<HTMLElement>;
        onPlayingCapture?: react.ReactEventHandler<HTMLElement>;
        onProgress?: react.ReactEventHandler<HTMLElement>;
        onProgressCapture?: react.ReactEventHandler<HTMLElement>;
        onRateChange?: react.ReactEventHandler<HTMLElement>;
        onRateChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeked?: react.ReactEventHandler<HTMLElement>;
        onSeekedCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeking?: react.ReactEventHandler<HTMLElement>;
        onSeekingCapture?: react.ReactEventHandler<HTMLElement>;
        onStalled?: react.ReactEventHandler<HTMLElement>;
        onStalledCapture?: react.ReactEventHandler<HTMLElement>;
        onSuspend?: react.ReactEventHandler<HTMLElement>;
        onSuspendCapture?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdate?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdateCapture?: react.ReactEventHandler<HTMLElement>;
        onVolumeChange?: react.ReactEventHandler<HTMLElement>;
        onVolumeChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onWaiting?: react.ReactEventHandler<HTMLElement>;
        onWaitingCapture?: react.ReactEventHandler<HTMLElement>;
        onAuxClick?: react.MouseEventHandler<HTMLElement>;
        onAuxClickCapture?: react.MouseEventHandler<HTMLElement>;
        onClick?: react.MouseEventHandler<HTMLElement>;
        onClickCapture?: react.MouseEventHandler<HTMLElement>;
        onContextMenu?: react.MouseEventHandler<HTMLElement>;
        onContextMenuCapture?: react.MouseEventHandler<HTMLElement>;
        onDoubleClick?: react.MouseEventHandler<HTMLElement>;
        onDoubleClickCapture?: react.MouseEventHandler<HTMLElement>;
        onDrag?: react.DragEventHandler<HTMLElement>;
        onDragCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnd?: react.DragEventHandler<HTMLElement>;
        onDragEndCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnter?: react.DragEventHandler<HTMLElement>;
        onDragEnterCapture?: react.DragEventHandler<HTMLElement>;
        onDragExit?: react.DragEventHandler<HTMLElement>;
        onDragExitCapture?: react.DragEventHandler<HTMLElement>;
        onDragLeave?: react.DragEventHandler<HTMLElement>;
        onDragLeaveCapture?: react.DragEventHandler<HTMLElement>;
        onDragOver?: react.DragEventHandler<HTMLElement>;
        onDragOverCapture?: react.DragEventHandler<HTMLElement>;
        onDragStart?: react.DragEventHandler<HTMLElement>;
        onDragStartCapture?: react.DragEventHandler<HTMLElement>;
        onDrop?: react.DragEventHandler<HTMLElement>;
        onDropCapture?: react.DragEventHandler<HTMLElement>;
        onMouseDown?: react.MouseEventHandler<HTMLElement>;
        onMouseDownCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseEnter?: react.MouseEventHandler<HTMLElement>;
        onMouseLeave?: react.MouseEventHandler<HTMLElement>;
        onMouseMove?: react.MouseEventHandler<HTMLElement>;
        onMouseMoveCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOut?: react.MouseEventHandler<HTMLElement>;
        onMouseOutCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOver?: react.MouseEventHandler<HTMLElement>;
        onMouseOverCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseUp?: react.MouseEventHandler<HTMLElement>;
        onMouseUpCapture?: react.MouseEventHandler<HTMLElement>;
        onSelect?: react.ReactEventHandler<HTMLElement>;
        onSelectCapture?: react.ReactEventHandler<HTMLElement>;
        onTouchCancel?: react.TouchEventHandler<HTMLElement>;
        onTouchCancelCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchEnd?: react.TouchEventHandler<HTMLElement>;
        onTouchEndCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchMove?: react.TouchEventHandler<HTMLElement>;
        onTouchMoveCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchStart?: react.TouchEventHandler<HTMLElement>;
        onTouchStartCapture?: react.TouchEventHandler<HTMLElement>;
        onPointerDown?: react.PointerEventHandler<HTMLElement>;
        onPointerDownCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerMove?: react.PointerEventHandler<HTMLElement>;
        onPointerMoveCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerUp?: react.PointerEventHandler<HTMLElement>;
        onPointerUpCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerCancel?: react.PointerEventHandler<HTMLElement>;
        onPointerCancelCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerEnter?: react.PointerEventHandler<HTMLElement>;
        onPointerLeave?: react.PointerEventHandler<HTMLElement>;
        onPointerOver?: react.PointerEventHandler<HTMLElement>;
        onPointerOverCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerOut?: react.PointerEventHandler<HTMLElement>;
        onPointerOutCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onScroll?: react.UIEventHandler<HTMLElement>;
        onScrollCapture?: react.UIEventHandler<HTMLElement>;
        onWheel?: react.WheelEventHandler<HTMLElement>;
        onWheelCapture?: react.WheelEventHandler<HTMLElement>;
        onAnimationStart?: react.AnimationEventHandler<HTMLElement>;
        onAnimationStartCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEnd?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEndCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIteration?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIterationCapture?: react.AnimationEventHandler<HTMLElement>;
        onTransitionEnd?: react.TransitionEventHandler<HTMLElement>;
        onTransitionEndCapture?: react.TransitionEventHandler<HTMLElement>;
    };
    indicatorProps: {
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: react.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: react.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        exportparts?: string | undefined;
        part?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        children?: react.ReactNode | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: react.ClipboardEventHandler<HTMLElement>;
        onCopyCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCut?: react.ClipboardEventHandler<HTMLElement>;
        onCutCapture?: react.ClipboardEventHandler<HTMLElement>;
        onPaste?: react.ClipboardEventHandler<HTMLElement>;
        onPasteCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCompositionEnd?: react.CompositionEventHandler<HTMLElement>;
        onCompositionEndCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStart?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStartCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdate?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdateCapture?: react.CompositionEventHandler<HTMLElement>;
        onFocus?: react.FocusEventHandler<HTMLElement>;
        onFocusCapture?: react.FocusEventHandler<HTMLElement>;
        onBlur?: react.FocusEventHandler<HTMLElement>;
        onBlurCapture?: react.FocusEventHandler<HTMLElement>;
        onChange?: react.FormEventHandler<HTMLElement>;
        onChangeCapture?: react.FormEventHandler<HTMLElement>;
        onBeforeInput?: react.InputEventHandler<HTMLElement>;
        onBeforeInputCapture?: react.FormEventHandler<HTMLElement>;
        onInput?: react.FormEventHandler<HTMLElement>;
        onInputCapture?: react.FormEventHandler<HTMLElement>;
        onReset?: react.FormEventHandler<HTMLElement>;
        onResetCapture?: react.FormEventHandler<HTMLElement>;
        onSubmit?: react.FormEventHandler<HTMLElement>;
        onSubmitCapture?: react.FormEventHandler<HTMLElement>;
        onInvalid?: react.FormEventHandler<HTMLElement>;
        onInvalidCapture?: react.FormEventHandler<HTMLElement>;
        onLoad?: react.ReactEventHandler<HTMLElement>;
        onLoadCapture?: react.ReactEventHandler<HTMLElement>;
        onError?: react.ReactEventHandler<HTMLElement>;
        onErrorCapture?: react.ReactEventHandler<HTMLElement>;
        onKeyDown?: react.KeyboardEventHandler<HTMLElement>;
        onKeyDownCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPress?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPressCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUp?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUpCapture?: react.KeyboardEventHandler<HTMLElement>;
        onAbort?: react.ReactEventHandler<HTMLElement>;
        onAbortCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlay?: react.ReactEventHandler<HTMLElement>;
        onCanPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThrough?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThroughCapture?: react.ReactEventHandler<HTMLElement>;
        onDurationChange?: react.ReactEventHandler<HTMLElement>;
        onDurationChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onEmptied?: react.ReactEventHandler<HTMLElement>;
        onEmptiedCapture?: react.ReactEventHandler<HTMLElement>;
        onEncrypted?: react.ReactEventHandler<HTMLElement>;
        onEncryptedCapture?: react.ReactEventHandler<HTMLElement>;
        onEnded?: react.ReactEventHandler<HTMLElement>;
        onEndedCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedData?: react.ReactEventHandler<HTMLElement>;
        onLoadedDataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadata?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadStart?: react.ReactEventHandler<HTMLElement>;
        onLoadStartCapture?: react.ReactEventHandler<HTMLElement>;
        onPause?: react.ReactEventHandler<HTMLElement>;
        onPauseCapture?: react.ReactEventHandler<HTMLElement>;
        onPlay?: react.ReactEventHandler<HTMLElement>;
        onPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onPlaying?: react.ReactEventHandler<HTMLElement>;
        onPlayingCapture?: react.ReactEventHandler<HTMLElement>;
        onProgress?: react.ReactEventHandler<HTMLElement>;
        onProgressCapture?: react.ReactEventHandler<HTMLElement>;
        onRateChange?: react.ReactEventHandler<HTMLElement>;
        onRateChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeked?: react.ReactEventHandler<HTMLElement>;
        onSeekedCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeking?: react.ReactEventHandler<HTMLElement>;
        onSeekingCapture?: react.ReactEventHandler<HTMLElement>;
        onStalled?: react.ReactEventHandler<HTMLElement>;
        onStalledCapture?: react.ReactEventHandler<HTMLElement>;
        onSuspend?: react.ReactEventHandler<HTMLElement>;
        onSuspendCapture?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdate?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdateCapture?: react.ReactEventHandler<HTMLElement>;
        onVolumeChange?: react.ReactEventHandler<HTMLElement>;
        onVolumeChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onWaiting?: react.ReactEventHandler<HTMLElement>;
        onWaitingCapture?: react.ReactEventHandler<HTMLElement>;
        onAuxClick?: react.MouseEventHandler<HTMLElement>;
        onAuxClickCapture?: react.MouseEventHandler<HTMLElement>;
        onClick?: react.MouseEventHandler<HTMLElement>;
        onClickCapture?: react.MouseEventHandler<HTMLElement>;
        onContextMenu?: react.MouseEventHandler<HTMLElement>;
        onContextMenuCapture?: react.MouseEventHandler<HTMLElement>;
        onDoubleClick?: react.MouseEventHandler<HTMLElement>;
        onDoubleClickCapture?: react.MouseEventHandler<HTMLElement>;
        onDrag?: react.DragEventHandler<HTMLElement>;
        onDragCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnd?: react.DragEventHandler<HTMLElement>;
        onDragEndCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnter?: react.DragEventHandler<HTMLElement>;
        onDragEnterCapture?: react.DragEventHandler<HTMLElement>;
        onDragExit?: react.DragEventHandler<HTMLElement>;
        onDragExitCapture?: react.DragEventHandler<HTMLElement>;
        onDragLeave?: react.DragEventHandler<HTMLElement>;
        onDragLeaveCapture?: react.DragEventHandler<HTMLElement>;
        onDragOver?: react.DragEventHandler<HTMLElement>;
        onDragOverCapture?: react.DragEventHandler<HTMLElement>;
        onDragStart?: react.DragEventHandler<HTMLElement>;
        onDragStartCapture?: react.DragEventHandler<HTMLElement>;
        onDrop?: react.DragEventHandler<HTMLElement>;
        onDropCapture?: react.DragEventHandler<HTMLElement>;
        onMouseDown?: react.MouseEventHandler<HTMLElement>;
        onMouseDownCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseEnter?: react.MouseEventHandler<HTMLElement>;
        onMouseLeave?: react.MouseEventHandler<HTMLElement>;
        onMouseMove?: react.MouseEventHandler<HTMLElement>;
        onMouseMoveCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOut?: react.MouseEventHandler<HTMLElement>;
        onMouseOutCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOver?: react.MouseEventHandler<HTMLElement>;
        onMouseOverCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseUp?: react.MouseEventHandler<HTMLElement>;
        onMouseUpCapture?: react.MouseEventHandler<HTMLElement>;
        onSelect?: react.ReactEventHandler<HTMLElement>;
        onSelectCapture?: react.ReactEventHandler<HTMLElement>;
        onTouchCancel?: react.TouchEventHandler<HTMLElement>;
        onTouchCancelCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchEnd?: react.TouchEventHandler<HTMLElement>;
        onTouchEndCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchMove?: react.TouchEventHandler<HTMLElement>;
        onTouchMoveCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchStart?: react.TouchEventHandler<HTMLElement>;
        onTouchStartCapture?: react.TouchEventHandler<HTMLElement>;
        onPointerDown?: react.PointerEventHandler<HTMLElement>;
        onPointerDownCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerMove?: react.PointerEventHandler<HTMLElement>;
        onPointerMoveCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerUp?: react.PointerEventHandler<HTMLElement>;
        onPointerUpCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerCancel?: react.PointerEventHandler<HTMLElement>;
        onPointerCancelCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerEnter?: react.PointerEventHandler<HTMLElement>;
        onPointerLeave?: react.PointerEventHandler<HTMLElement>;
        onPointerOver?: react.PointerEventHandler<HTMLElement>;
        onPointerOverCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerOut?: react.PointerEventHandler<HTMLElement>;
        onPointerOutCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onScroll?: react.UIEventHandler<HTMLElement>;
        onScrollCapture?: react.UIEventHandler<HTMLElement>;
        onWheel?: react.WheelEventHandler<HTMLElement>;
        onWheelCapture?: react.WheelEventHandler<HTMLElement>;
        onAnimationStart?: react.AnimationEventHandler<HTMLElement>;
        onAnimationStartCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEnd?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEndCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIteration?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIterationCapture?: react.AnimationEventHandler<HTMLElement>;
        onTransitionEnd?: react.TransitionEventHandler<HTMLElement>;
        onTransitionEndCapture?: react.TransitionEventHandler<HTMLElement>;
    };
    getIndicatorRenderProps: () => {
        minValue: number;
        maxValue: number;
        value: number;
        style: {
            opacity: number;
        };
    };
    contentProps: {
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: react.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: react.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        exportparts?: string | undefined;
        part?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        children?: react.ReactNode | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: react.ClipboardEventHandler<HTMLElement>;
        onCopyCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCut?: react.ClipboardEventHandler<HTMLElement>;
        onCutCapture?: react.ClipboardEventHandler<HTMLElement>;
        onPaste?: react.ClipboardEventHandler<HTMLElement>;
        onPasteCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCompositionEnd?: react.CompositionEventHandler<HTMLElement>;
        onCompositionEndCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStart?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStartCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdate?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdateCapture?: react.CompositionEventHandler<HTMLElement>;
        onFocus?: react.FocusEventHandler<HTMLElement>;
        onFocusCapture?: react.FocusEventHandler<HTMLElement>;
        onBlur?: react.FocusEventHandler<HTMLElement>;
        onBlurCapture?: react.FocusEventHandler<HTMLElement>;
        onChange?: react.FormEventHandler<HTMLElement>;
        onChangeCapture?: react.FormEventHandler<HTMLElement>;
        onBeforeInput?: react.InputEventHandler<HTMLElement>;
        onBeforeInputCapture?: react.FormEventHandler<HTMLElement>;
        onInput?: react.FormEventHandler<HTMLElement>;
        onInputCapture?: react.FormEventHandler<HTMLElement>;
        onReset?: react.FormEventHandler<HTMLElement>;
        onResetCapture?: react.FormEventHandler<HTMLElement>;
        onSubmit?: react.FormEventHandler<HTMLElement>;
        onSubmitCapture?: react.FormEventHandler<HTMLElement>;
        onInvalid?: react.FormEventHandler<HTMLElement>;
        onInvalidCapture?: react.FormEventHandler<HTMLElement>;
        onLoad?: react.ReactEventHandler<HTMLElement>;
        onLoadCapture?: react.ReactEventHandler<HTMLElement>;
        onError?: react.ReactEventHandler<HTMLElement>;
        onErrorCapture?: react.ReactEventHandler<HTMLElement>;
        onKeyDown?: react.KeyboardEventHandler<HTMLElement>;
        onKeyDownCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPress?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPressCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUp?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUpCapture?: react.KeyboardEventHandler<HTMLElement>;
        onAbort?: react.ReactEventHandler<HTMLElement>;
        onAbortCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlay?: react.ReactEventHandler<HTMLElement>;
        onCanPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThrough?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThroughCapture?: react.ReactEventHandler<HTMLElement>;
        onDurationChange?: react.ReactEventHandler<HTMLElement>;
        onDurationChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onEmptied?: react.ReactEventHandler<HTMLElement>;
        onEmptiedCapture?: react.ReactEventHandler<HTMLElement>;
        onEncrypted?: react.ReactEventHandler<HTMLElement>;
        onEncryptedCapture?: react.ReactEventHandler<HTMLElement>;
        onEnded?: react.ReactEventHandler<HTMLElement>;
        onEndedCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedData?: react.ReactEventHandler<HTMLElement>;
        onLoadedDataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadata?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadStart?: react.ReactEventHandler<HTMLElement>;
        onLoadStartCapture?: react.ReactEventHandler<HTMLElement>;
        onPause?: react.ReactEventHandler<HTMLElement>;
        onPauseCapture?: react.ReactEventHandler<HTMLElement>;
        onPlay?: react.ReactEventHandler<HTMLElement>;
        onPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onPlaying?: react.ReactEventHandler<HTMLElement>;
        onPlayingCapture?: react.ReactEventHandler<HTMLElement>;
        onProgress?: react.ReactEventHandler<HTMLElement>;
        onProgressCapture?: react.ReactEventHandler<HTMLElement>;
        onRateChange?: react.ReactEventHandler<HTMLElement>;
        onRateChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeked?: react.ReactEventHandler<HTMLElement>;
        onSeekedCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeking?: react.ReactEventHandler<HTMLElement>;
        onSeekingCapture?: react.ReactEventHandler<HTMLElement>;
        onStalled?: react.ReactEventHandler<HTMLElement>;
        onStalledCapture?: react.ReactEventHandler<HTMLElement>;
        onSuspend?: react.ReactEventHandler<HTMLElement>;
        onSuspendCapture?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdate?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdateCapture?: react.ReactEventHandler<HTMLElement>;
        onVolumeChange?: react.ReactEventHandler<HTMLElement>;
        onVolumeChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onWaiting?: react.ReactEventHandler<HTMLElement>;
        onWaitingCapture?: react.ReactEventHandler<HTMLElement>;
        onAuxClick?: react.MouseEventHandler<HTMLElement>;
        onAuxClickCapture?: react.MouseEventHandler<HTMLElement>;
        onClick?: react.MouseEventHandler<HTMLElement>;
        onClickCapture?: react.MouseEventHandler<HTMLElement>;
        onContextMenu?: react.MouseEventHandler<HTMLElement>;
        onContextMenuCapture?: react.MouseEventHandler<HTMLElement>;
        onDoubleClick?: react.MouseEventHandler<HTMLElement>;
        onDoubleClickCapture?: react.MouseEventHandler<HTMLElement>;
        onDrag?: react.DragEventHandler<HTMLElement>;
        onDragCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnd?: react.DragEventHandler<HTMLElement>;
        onDragEndCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnter?: react.DragEventHandler<HTMLElement>;
        onDragEnterCapture?: react.DragEventHandler<HTMLElement>;
        onDragExit?: react.DragEventHandler<HTMLElement>;
        onDragExitCapture?: react.DragEventHandler<HTMLElement>;
        onDragLeave?: react.DragEventHandler<HTMLElement>;
        onDragLeaveCapture?: react.DragEventHandler<HTMLElement>;
        onDragOver?: react.DragEventHandler<HTMLElement>;
        onDragOverCapture?: react.DragEventHandler<HTMLElement>;
        onDragStart?: react.DragEventHandler<HTMLElement>;
        onDragStartCapture?: react.DragEventHandler<HTMLElement>;
        onDrop?: react.DragEventHandler<HTMLElement>;
        onDropCapture?: react.DragEventHandler<HTMLElement>;
        onMouseDown?: react.MouseEventHandler<HTMLElement>;
        onMouseDownCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseEnter?: react.MouseEventHandler<HTMLElement>;
        onMouseLeave?: react.MouseEventHandler<HTMLElement>;
        onMouseMove?: react.MouseEventHandler<HTMLElement>;
        onMouseMoveCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOut?: react.MouseEventHandler<HTMLElement>;
        onMouseOutCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOver?: react.MouseEventHandler<HTMLElement>;
        onMouseOverCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseUp?: react.MouseEventHandler<HTMLElement>;
        onMouseUpCapture?: react.MouseEventHandler<HTMLElement>;
        onSelect?: react.ReactEventHandler<HTMLElement>;
        onSelectCapture?: react.ReactEventHandler<HTMLElement>;
        onTouchCancel?: react.TouchEventHandler<HTMLElement>;
        onTouchCancelCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchEnd?: react.TouchEventHandler<HTMLElement>;
        onTouchEndCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchMove?: react.TouchEventHandler<HTMLElement>;
        onTouchMoveCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchStart?: react.TouchEventHandler<HTMLElement>;
        onTouchStartCapture?: react.TouchEventHandler<HTMLElement>;
        onPointerDown?: react.PointerEventHandler<HTMLElement>;
        onPointerDownCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerMove?: react.PointerEventHandler<HTMLElement>;
        onPointerMoveCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerUp?: react.PointerEventHandler<HTMLElement>;
        onPointerUpCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerCancel?: react.PointerEventHandler<HTMLElement>;
        onPointerCancelCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerEnter?: react.PointerEventHandler<HTMLElement>;
        onPointerLeave?: react.PointerEventHandler<HTMLElement>;
        onPointerOver?: react.PointerEventHandler<HTMLElement>;
        onPointerOverCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerOut?: react.PointerEventHandler<HTMLElement>;
        onPointerOutCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onScroll?: react.UIEventHandler<HTMLElement>;
        onScrollCapture?: react.UIEventHandler<HTMLElement>;
        onWheel?: react.WheelEventHandler<HTMLElement>;
        onWheelCapture?: react.WheelEventHandler<HTMLElement>;
        onAnimationStart?: react.AnimationEventHandler<HTMLElement>;
        onAnimationStartCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEnd?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEndCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIteration?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIterationCapture?: react.AnimationEventHandler<HTMLElement>;
        onTransitionEnd?: react.TransitionEventHandler<HTMLElement>;
        onTransitionEndCapture?: react.TransitionEventHandler<HTMLElement>;
    };
};

interface PullToRefreshRootProps extends UsePullToRefreshProps, PrimitiveProps, React.HTMLAttributes<HTMLDivElement> {
}
declare const PullToRefreshRoot: react.ForwardRefExoticComponent<PullToRefreshRootProps & react.RefAttributes<HTMLDivElement>>;
interface PullToRefreshIndicatorProps extends Omit<React.HTMLAttributes<HTMLDivElement>, "children"> {
    children: (props: PullToRefreshIndicatorRenderProps) => React.ReactNode;
}
declare const PullToRefreshIndicator: (props: PullToRefreshIndicatorProps) => react_jsx_runtime.JSX.Element;
interface PullToRefreshContentProps extends PrimitiveProps, React.HTMLAttributes<HTMLDivElement> {
}
declare const PullToRefreshContent: react.ForwardRefExoticComponent<PullToRefreshContentProps & react.RefAttributes<HTMLDivElement>>;

interface UsePullToRefreshContext extends UsePullToRefreshReturn {
}
declare function usePullToRefreshContext<T extends boolean | undefined = true>({ strict, }?: {
    strict?: T;
}): T extends false ? UsePullToRefreshContext | null : UsePullToRefreshContext;

declare const pullToRefreshPreventPull: {
    "data-seed-pull-to-refresh-prevent-pull": string;
};

declare namespace PullToRefresh_namespace {
  export { PullToRefreshContent as Content, PullToRefreshIndicator as Indicator, PullToRefreshRoot as Root, pullToRefreshPreventPull as preventPull };
  export type { PullToRefreshContentProps as ContentProps, PullToRefreshIndicatorProps as IndicatorProps, PullToRefreshRootProps as RootProps };
}

export { PullToRefresh_namespace as PullToRefresh, PullToRefreshContent, PullToRefreshIndicator, PullToRefreshRoot, pullToRefreshPreventPull, usePullToRefreshContext };
export type { PullToRefreshContentProps, PullToRefreshIndicatorProps, PullToRefreshRootProps, UsePullToRefreshContext };
