import { PrimitiveProps } from '@grape-design/react-primitive';
import * as react from 'react';

interface UseSwitchStateProps {
    checked?: boolean;
    defaultChecked?: boolean;
    onCheckedChange?: (checked: boolean) => void;
}
interface UseSwitchProps extends UseSwitchStateProps {
    disabled?: boolean;
    invalid?: boolean;
    required?: boolean;
}
type UseSwitchReturn = ReturnType<typeof useSwitch>;
declare function useSwitch(props: UseSwitchProps): {
    checked: boolean;
    setChecked: (value: react.SetStateAction<boolean>) => void;
    focused: boolean;
    setFocused: react.Dispatch<react.SetStateAction<boolean>>;
    focusVisible: boolean;
    setFocusVisible: react.Dispatch<react.SetStateAction<boolean>>;
    stateProps: {
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: react.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: react.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        exportparts?: string | undefined;
        part?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        children?: react.ReactNode | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: react.ClipboardEventHandler<HTMLElement>;
        onCopyCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCut?: react.ClipboardEventHandler<HTMLElement>;
        onCutCapture?: react.ClipboardEventHandler<HTMLElement>;
        onPaste?: react.ClipboardEventHandler<HTMLElement>;
        onPasteCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCompositionEnd?: react.CompositionEventHandler<HTMLElement>;
        onCompositionEndCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStart?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStartCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdate?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdateCapture?: react.CompositionEventHandler<HTMLElement>;
        onFocus?: react.FocusEventHandler<HTMLElement>;
        onFocusCapture?: react.FocusEventHandler<HTMLElement>;
        onBlur?: react.FocusEventHandler<HTMLElement>;
        onBlurCapture?: react.FocusEventHandler<HTMLElement>;
        onChange?: react.FormEventHandler<HTMLElement>;
        onChangeCapture?: react.FormEventHandler<HTMLElement>;
        onBeforeInput?: react.InputEventHandler<HTMLElement>;
        onBeforeInputCapture?: react.FormEventHandler<HTMLElement>;
        onInput?: react.FormEventHandler<HTMLElement>;
        onInputCapture?: react.FormEventHandler<HTMLElement>;
        onReset?: react.FormEventHandler<HTMLElement>;
        onResetCapture?: react.FormEventHandler<HTMLElement>;
        onSubmit?: react.FormEventHandler<HTMLElement>;
        onSubmitCapture?: react.FormEventHandler<HTMLElement>;
        onInvalid?: react.FormEventHandler<HTMLElement>;
        onInvalidCapture?: react.FormEventHandler<HTMLElement>;
        onLoad?: react.ReactEventHandler<HTMLElement>;
        onLoadCapture?: react.ReactEventHandler<HTMLElement>;
        onError?: react.ReactEventHandler<HTMLElement>;
        onErrorCapture?: react.ReactEventHandler<HTMLElement>;
        onKeyDown?: react.KeyboardEventHandler<HTMLElement>;
        onKeyDownCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPress?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPressCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUp?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUpCapture?: react.KeyboardEventHandler<HTMLElement>;
        onAbort?: react.ReactEventHandler<HTMLElement>;
        onAbortCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlay?: react.ReactEventHandler<HTMLElement>;
        onCanPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThrough?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThroughCapture?: react.ReactEventHandler<HTMLElement>;
        onDurationChange?: react.ReactEventHandler<HTMLElement>;
        onDurationChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onEmptied?: react.ReactEventHandler<HTMLElement>;
        onEmptiedCapture?: react.ReactEventHandler<HTMLElement>;
        onEncrypted?: react.ReactEventHandler<HTMLElement>;
        onEncryptedCapture?: react.ReactEventHandler<HTMLElement>;
        onEnded?: react.ReactEventHandler<HTMLElement>;
        onEndedCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedData?: react.ReactEventHandler<HTMLElement>;
        onLoadedDataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadata?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadStart?: react.ReactEventHandler<HTMLElement>;
        onLoadStartCapture?: react.ReactEventHandler<HTMLElement>;
        onPause?: react.ReactEventHandler<HTMLElement>;
        onPauseCapture?: react.ReactEventHandler<HTMLElement>;
        onPlay?: react.ReactEventHandler<HTMLElement>;
        onPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onPlaying?: react.ReactEventHandler<HTMLElement>;
        onPlayingCapture?: react.ReactEventHandler<HTMLElement>;
        onProgress?: react.ReactEventHandler<HTMLElement>;
        onProgressCapture?: react.ReactEventHandler<HTMLElement>;
        onRateChange?: react.ReactEventHandler<HTMLElement>;
        onRateChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeked?: react.ReactEventHandler<HTMLElement>;
        onSeekedCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeking?: react.ReactEventHandler<HTMLElement>;
        onSeekingCapture?: react.ReactEventHandler<HTMLElement>;
        onStalled?: react.ReactEventHandler<HTMLElement>;
        onStalledCapture?: react.ReactEventHandler<HTMLElement>;
        onSuspend?: react.ReactEventHandler<HTMLElement>;
        onSuspendCapture?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdate?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdateCapture?: react.ReactEventHandler<HTMLElement>;
        onVolumeChange?: react.ReactEventHandler<HTMLElement>;
        onVolumeChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onWaiting?: react.ReactEventHandler<HTMLElement>;
        onWaitingCapture?: react.ReactEventHandler<HTMLElement>;
        onAuxClick?: react.MouseEventHandler<HTMLElement>;
        onAuxClickCapture?: react.MouseEventHandler<HTMLElement>;
        onClick?: react.MouseEventHandler<HTMLElement>;
        onClickCapture?: react.MouseEventHandler<HTMLElement>;
        onContextMenu?: react.MouseEventHandler<HTMLElement>;
        onContextMenuCapture?: react.MouseEventHandler<HTMLElement>;
        onDoubleClick?: react.MouseEventHandler<HTMLElement>;
        onDoubleClickCapture?: react.MouseEventHandler<HTMLElement>;
        onDrag?: react.DragEventHandler<HTMLElement>;
        onDragCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnd?: react.DragEventHandler<HTMLElement>;
        onDragEndCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnter?: react.DragEventHandler<HTMLElement>;
        onDragEnterCapture?: react.DragEventHandler<HTMLElement>;
        onDragExit?: react.DragEventHandler<HTMLElement>;
        onDragExitCapture?: react.DragEventHandler<HTMLElement>;
        onDragLeave?: react.DragEventHandler<HTMLElement>;
        onDragLeaveCapture?: react.DragEventHandler<HTMLElement>;
        onDragOver?: react.DragEventHandler<HTMLElement>;
        onDragOverCapture?: react.DragEventHandler<HTMLElement>;
        onDragStart?: react.DragEventHandler<HTMLElement>;
        onDragStartCapture?: react.DragEventHandler<HTMLElement>;
        onDrop?: react.DragEventHandler<HTMLElement>;
        onDropCapture?: react.DragEventHandler<HTMLElement>;
        onMouseDown?: react.MouseEventHandler<HTMLElement>;
        onMouseDownCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseEnter?: react.MouseEventHandler<HTMLElement>;
        onMouseLeave?: react.MouseEventHandler<HTMLElement>;
        onMouseMove?: react.MouseEventHandler<HTMLElement>;
        onMouseMoveCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOut?: react.MouseEventHandler<HTMLElement>;
        onMouseOutCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOver?: react.MouseEventHandler<HTMLElement>;
        onMouseOverCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseUp?: react.MouseEventHandler<HTMLElement>;
        onMouseUpCapture?: react.MouseEventHandler<HTMLElement>;
        onSelect?: react.ReactEventHandler<HTMLElement>;
        onSelectCapture?: react.ReactEventHandler<HTMLElement>;
        onTouchCancel?: react.TouchEventHandler<HTMLElement>;
        onTouchCancelCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchEnd?: react.TouchEventHandler<HTMLElement>;
        onTouchEndCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchMove?: react.TouchEventHandler<HTMLElement>;
        onTouchMoveCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchStart?: react.TouchEventHandler<HTMLElement>;
        onTouchStartCapture?: react.TouchEventHandler<HTMLElement>;
        onPointerDown?: react.PointerEventHandler<HTMLElement>;
        onPointerDownCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerMove?: react.PointerEventHandler<HTMLElement>;
        onPointerMoveCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerUp?: react.PointerEventHandler<HTMLElement>;
        onPointerUpCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerCancel?: react.PointerEventHandler<HTMLElement>;
        onPointerCancelCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerEnter?: react.PointerEventHandler<HTMLElement>;
        onPointerLeave?: react.PointerEventHandler<HTMLElement>;
        onPointerOver?: react.PointerEventHandler<HTMLElement>;
        onPointerOverCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerOut?: react.PointerEventHandler<HTMLElement>;
        onPointerOutCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onScroll?: react.UIEventHandler<HTMLElement>;
        onScrollCapture?: react.UIEventHandler<HTMLElement>;
        onWheel?: react.WheelEventHandler<HTMLElement>;
        onWheelCapture?: react.WheelEventHandler<HTMLElement>;
        onAnimationStart?: react.AnimationEventHandler<HTMLElement>;
        onAnimationStartCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEnd?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEndCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIteration?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIterationCapture?: react.AnimationEventHandler<HTMLElement>;
        onTransitionEnd?: react.TransitionEventHandler<HTMLElement>;
        onTransitionEndCapture?: react.TransitionEventHandler<HTMLElement>;
    };
    rootProps: {
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: react.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: react.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        exportparts?: string | undefined;
        part?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        children?: react.ReactNode | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: react.ClipboardEventHandler<HTMLLabelElement>;
        onCopyCapture?: react.ClipboardEventHandler<HTMLLabelElement>;
        onCut?: react.ClipboardEventHandler<HTMLLabelElement>;
        onCutCapture?: react.ClipboardEventHandler<HTMLLabelElement>;
        onPaste?: react.ClipboardEventHandler<HTMLLabelElement>;
        onPasteCapture?: react.ClipboardEventHandler<HTMLLabelElement>;
        onCompositionEnd?: react.CompositionEventHandler<HTMLLabelElement>;
        onCompositionEndCapture?: react.CompositionEventHandler<HTMLLabelElement>;
        onCompositionStart?: react.CompositionEventHandler<HTMLLabelElement>;
        onCompositionStartCapture?: react.CompositionEventHandler<HTMLLabelElement>;
        onCompositionUpdate?: react.CompositionEventHandler<HTMLLabelElement>;
        onCompositionUpdateCapture?: react.CompositionEventHandler<HTMLLabelElement>;
        onFocus?: react.FocusEventHandler<HTMLLabelElement>;
        onFocusCapture?: react.FocusEventHandler<HTMLLabelElement>;
        onBlur?: react.FocusEventHandler<HTMLLabelElement>;
        onBlurCapture?: react.FocusEventHandler<HTMLLabelElement>;
        onChange?: react.FormEventHandler<HTMLLabelElement>;
        onChangeCapture?: react.FormEventHandler<HTMLLabelElement>;
        onBeforeInput?: react.InputEventHandler<HTMLLabelElement>;
        onBeforeInputCapture?: react.FormEventHandler<HTMLLabelElement>;
        onInput?: react.FormEventHandler<HTMLLabelElement>;
        onInputCapture?: react.FormEventHandler<HTMLLabelElement>;
        onReset?: react.FormEventHandler<HTMLLabelElement>;
        onResetCapture?: react.FormEventHandler<HTMLLabelElement>;
        onSubmit?: react.FormEventHandler<HTMLLabelElement>;
        onSubmitCapture?: react.FormEventHandler<HTMLLabelElement>;
        onInvalid?: react.FormEventHandler<HTMLLabelElement>;
        onInvalidCapture?: react.FormEventHandler<HTMLLabelElement>;
        onLoad?: react.ReactEventHandler<HTMLLabelElement>;
        onLoadCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onError?: react.ReactEventHandler<HTMLLabelElement>;
        onErrorCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onKeyDown?: react.KeyboardEventHandler<HTMLLabelElement>;
        onKeyDownCapture?: react.KeyboardEventHandler<HTMLLabelElement>;
        onKeyPress?: react.KeyboardEventHandler<HTMLLabelElement>;
        onKeyPressCapture?: react.KeyboardEventHandler<HTMLLabelElement>;
        onKeyUp?: react.KeyboardEventHandler<HTMLLabelElement>;
        onKeyUpCapture?: react.KeyboardEventHandler<HTMLLabelElement>;
        onAbort?: react.ReactEventHandler<HTMLLabelElement>;
        onAbortCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onCanPlay?: react.ReactEventHandler<HTMLLabelElement>;
        onCanPlayCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onCanPlayThrough?: react.ReactEventHandler<HTMLLabelElement>;
        onCanPlayThroughCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onDurationChange?: react.ReactEventHandler<HTMLLabelElement>;
        onDurationChangeCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onEmptied?: react.ReactEventHandler<HTMLLabelElement>;
        onEmptiedCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onEncrypted?: react.ReactEventHandler<HTMLLabelElement>;
        onEncryptedCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onEnded?: react.ReactEventHandler<HTMLLabelElement>;
        onEndedCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onLoadedData?: react.ReactEventHandler<HTMLLabelElement>;
        onLoadedDataCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onLoadedMetadata?: react.ReactEventHandler<HTMLLabelElement>;
        onLoadedMetadataCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onLoadStart?: react.ReactEventHandler<HTMLLabelElement>;
        onLoadStartCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onPause?: react.ReactEventHandler<HTMLLabelElement>;
        onPauseCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onPlay?: react.ReactEventHandler<HTMLLabelElement>;
        onPlayCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onPlaying?: react.ReactEventHandler<HTMLLabelElement>;
        onPlayingCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onProgress?: react.ReactEventHandler<HTMLLabelElement>;
        onProgressCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onRateChange?: react.ReactEventHandler<HTMLLabelElement>;
        onRateChangeCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onSeeked?: react.ReactEventHandler<HTMLLabelElement>;
        onSeekedCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onSeeking?: react.ReactEventHandler<HTMLLabelElement>;
        onSeekingCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onStalled?: react.ReactEventHandler<HTMLLabelElement>;
        onStalledCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onSuspend?: react.ReactEventHandler<HTMLLabelElement>;
        onSuspendCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onTimeUpdate?: react.ReactEventHandler<HTMLLabelElement>;
        onTimeUpdateCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onVolumeChange?: react.ReactEventHandler<HTMLLabelElement>;
        onVolumeChangeCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onWaiting?: react.ReactEventHandler<HTMLLabelElement>;
        onWaitingCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onAuxClick?: react.MouseEventHandler<HTMLLabelElement>;
        onAuxClickCapture?: react.MouseEventHandler<HTMLLabelElement>;
        onClick?: react.MouseEventHandler<HTMLLabelElement>;
        onClickCapture?: react.MouseEventHandler<HTMLLabelElement>;
        onContextMenu?: react.MouseEventHandler<HTMLLabelElement>;
        onContextMenuCapture?: react.MouseEventHandler<HTMLLabelElement>;
        onDoubleClick?: react.MouseEventHandler<HTMLLabelElement>;
        onDoubleClickCapture?: react.MouseEventHandler<HTMLLabelElement>;
        onDrag?: react.DragEventHandler<HTMLLabelElement>;
        onDragCapture?: react.DragEventHandler<HTMLLabelElement>;
        onDragEnd?: react.DragEventHandler<HTMLLabelElement>;
        onDragEndCapture?: react.DragEventHandler<HTMLLabelElement>;
        onDragEnter?: react.DragEventHandler<HTMLLabelElement>;
        onDragEnterCapture?: react.DragEventHandler<HTMLLabelElement>;
        onDragExit?: react.DragEventHandler<HTMLLabelElement>;
        onDragExitCapture?: react.DragEventHandler<HTMLLabelElement>;
        onDragLeave?: react.DragEventHandler<HTMLLabelElement>;
        onDragLeaveCapture?: react.DragEventHandler<HTMLLabelElement>;
        onDragOver?: react.DragEventHandler<HTMLLabelElement>;
        onDragOverCapture?: react.DragEventHandler<HTMLLabelElement>;
        onDragStart?: react.DragEventHandler<HTMLLabelElement>;
        onDragStartCapture?: react.DragEventHandler<HTMLLabelElement>;
        onDrop?: react.DragEventHandler<HTMLLabelElement>;
        onDropCapture?: react.DragEventHandler<HTMLLabelElement>;
        onMouseDown?: react.MouseEventHandler<HTMLLabelElement>;
        onMouseDownCapture?: react.MouseEventHandler<HTMLLabelElement>;
        onMouseEnter?: react.MouseEventHandler<HTMLLabelElement>;
        onMouseLeave?: react.MouseEventHandler<HTMLLabelElement>;
        onMouseMove?: react.MouseEventHandler<HTMLLabelElement>;
        onMouseMoveCapture?: react.MouseEventHandler<HTMLLabelElement>;
        onMouseOut?: react.MouseEventHandler<HTMLLabelElement>;
        onMouseOutCapture?: react.MouseEventHandler<HTMLLabelElement>;
        onMouseOver?: react.MouseEventHandler<HTMLLabelElement>;
        onMouseOverCapture?: react.MouseEventHandler<HTMLLabelElement>;
        onMouseUp?: react.MouseEventHandler<HTMLLabelElement>;
        onMouseUpCapture?: react.MouseEventHandler<HTMLLabelElement>;
        onSelect?: react.ReactEventHandler<HTMLLabelElement>;
        onSelectCapture?: react.ReactEventHandler<HTMLLabelElement>;
        onTouchCancel?: react.TouchEventHandler<HTMLLabelElement>;
        onTouchCancelCapture?: react.TouchEventHandler<HTMLLabelElement>;
        onTouchEnd?: react.TouchEventHandler<HTMLLabelElement>;
        onTouchEndCapture?: react.TouchEventHandler<HTMLLabelElement>;
        onTouchMove?: react.TouchEventHandler<HTMLLabelElement>;
        onTouchMoveCapture?: react.TouchEventHandler<HTMLLabelElement>;
        onTouchStart?: react.TouchEventHandler<HTMLLabelElement>;
        onTouchStartCapture?: react.TouchEventHandler<HTMLLabelElement>;
        onPointerDown?: react.PointerEventHandler<HTMLLabelElement>;
        onPointerDownCapture?: react.PointerEventHandler<HTMLLabelElement>;
        onPointerMove?: react.PointerEventHandler<HTMLLabelElement>;
        onPointerMoveCapture?: react.PointerEventHandler<HTMLLabelElement>;
        onPointerUp?: react.PointerEventHandler<HTMLLabelElement>;
        onPointerUpCapture?: react.PointerEventHandler<HTMLLabelElement>;
        onPointerCancel?: react.PointerEventHandler<HTMLLabelElement>;
        onPointerCancelCapture?: react.PointerEventHandler<HTMLLabelElement>;
        onPointerEnter?: react.PointerEventHandler<HTMLLabelElement>;
        onPointerLeave?: react.PointerEventHandler<HTMLLabelElement>;
        onPointerOver?: react.PointerEventHandler<HTMLLabelElement>;
        onPointerOverCapture?: react.PointerEventHandler<HTMLLabelElement>;
        onPointerOut?: react.PointerEventHandler<HTMLLabelElement>;
        onPointerOutCapture?: react.PointerEventHandler<HTMLLabelElement>;
        onGotPointerCapture?: react.PointerEventHandler<HTMLLabelElement>;
        onGotPointerCaptureCapture?: react.PointerEventHandler<HTMLLabelElement>;
        onLostPointerCapture?: react.PointerEventHandler<HTMLLabelElement>;
        onLostPointerCaptureCapture?: react.PointerEventHandler<HTMLLabelElement>;
        onScroll?: react.UIEventHandler<HTMLLabelElement>;
        onScrollCapture?: react.UIEventHandler<HTMLLabelElement>;
        onWheel?: react.WheelEventHandler<HTMLLabelElement>;
        onWheelCapture?: react.WheelEventHandler<HTMLLabelElement>;
        onAnimationStart?: react.AnimationEventHandler<HTMLLabelElement>;
        onAnimationStartCapture?: react.AnimationEventHandler<HTMLLabelElement>;
        onAnimationEnd?: react.AnimationEventHandler<HTMLLabelElement>;
        onAnimationEndCapture?: react.AnimationEventHandler<HTMLLabelElement>;
        onAnimationIteration?: react.AnimationEventHandler<HTMLLabelElement>;
        onAnimationIterationCapture?: react.AnimationEventHandler<HTMLLabelElement>;
        onTransitionEnd?: react.TransitionEventHandler<HTMLLabelElement>;
        onTransitionEndCapture?: react.TransitionEventHandler<HTMLLabelElement>;
        form?: string | undefined;
        htmlFor?: string | undefined;
    };
    controlProps: {
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: react.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: react.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        exportparts?: string | undefined;
        part?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        children?: react.ReactNode | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: react.ClipboardEventHandler<HTMLElement>;
        onCopyCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCut?: react.ClipboardEventHandler<HTMLElement>;
        onCutCapture?: react.ClipboardEventHandler<HTMLElement>;
        onPaste?: react.ClipboardEventHandler<HTMLElement>;
        onPasteCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCompositionEnd?: react.CompositionEventHandler<HTMLElement>;
        onCompositionEndCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStart?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStartCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdate?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdateCapture?: react.CompositionEventHandler<HTMLElement>;
        onFocus?: react.FocusEventHandler<HTMLElement>;
        onFocusCapture?: react.FocusEventHandler<HTMLElement>;
        onBlur?: react.FocusEventHandler<HTMLElement>;
        onBlurCapture?: react.FocusEventHandler<HTMLElement>;
        onChange?: react.FormEventHandler<HTMLElement>;
        onChangeCapture?: react.FormEventHandler<HTMLElement>;
        onBeforeInput?: react.InputEventHandler<HTMLElement>;
        onBeforeInputCapture?: react.FormEventHandler<HTMLElement>;
        onInput?: react.FormEventHandler<HTMLElement>;
        onInputCapture?: react.FormEventHandler<HTMLElement>;
        onReset?: react.FormEventHandler<HTMLElement>;
        onResetCapture?: react.FormEventHandler<HTMLElement>;
        onSubmit?: react.FormEventHandler<HTMLElement>;
        onSubmitCapture?: react.FormEventHandler<HTMLElement>;
        onInvalid?: react.FormEventHandler<HTMLElement>;
        onInvalidCapture?: react.FormEventHandler<HTMLElement>;
        onLoad?: react.ReactEventHandler<HTMLElement>;
        onLoadCapture?: react.ReactEventHandler<HTMLElement>;
        onError?: react.ReactEventHandler<HTMLElement>;
        onErrorCapture?: react.ReactEventHandler<HTMLElement>;
        onKeyDown?: react.KeyboardEventHandler<HTMLElement>;
        onKeyDownCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPress?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPressCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUp?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUpCapture?: react.KeyboardEventHandler<HTMLElement>;
        onAbort?: react.ReactEventHandler<HTMLElement>;
        onAbortCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlay?: react.ReactEventHandler<HTMLElement>;
        onCanPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThrough?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThroughCapture?: react.ReactEventHandler<HTMLElement>;
        onDurationChange?: react.ReactEventHandler<HTMLElement>;
        onDurationChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onEmptied?: react.ReactEventHandler<HTMLElement>;
        onEmptiedCapture?: react.ReactEventHandler<HTMLElement>;
        onEncrypted?: react.ReactEventHandler<HTMLElement>;
        onEncryptedCapture?: react.ReactEventHandler<HTMLElement>;
        onEnded?: react.ReactEventHandler<HTMLElement>;
        onEndedCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedData?: react.ReactEventHandler<HTMLElement>;
        onLoadedDataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadata?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadStart?: react.ReactEventHandler<HTMLElement>;
        onLoadStartCapture?: react.ReactEventHandler<HTMLElement>;
        onPause?: react.ReactEventHandler<HTMLElement>;
        onPauseCapture?: react.ReactEventHandler<HTMLElement>;
        onPlay?: react.ReactEventHandler<HTMLElement>;
        onPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onPlaying?: react.ReactEventHandler<HTMLElement>;
        onPlayingCapture?: react.ReactEventHandler<HTMLElement>;
        onProgress?: react.ReactEventHandler<HTMLElement>;
        onProgressCapture?: react.ReactEventHandler<HTMLElement>;
        onRateChange?: react.ReactEventHandler<HTMLElement>;
        onRateChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeked?: react.ReactEventHandler<HTMLElement>;
        onSeekedCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeking?: react.ReactEventHandler<HTMLElement>;
        onSeekingCapture?: react.ReactEventHandler<HTMLElement>;
        onStalled?: react.ReactEventHandler<HTMLElement>;
        onStalledCapture?: react.ReactEventHandler<HTMLElement>;
        onSuspend?: react.ReactEventHandler<HTMLElement>;
        onSuspendCapture?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdate?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdateCapture?: react.ReactEventHandler<HTMLElement>;
        onVolumeChange?: react.ReactEventHandler<HTMLElement>;
        onVolumeChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onWaiting?: react.ReactEventHandler<HTMLElement>;
        onWaitingCapture?: react.ReactEventHandler<HTMLElement>;
        onAuxClick?: react.MouseEventHandler<HTMLElement>;
        onAuxClickCapture?: react.MouseEventHandler<HTMLElement>;
        onClick?: react.MouseEventHandler<HTMLElement>;
        onClickCapture?: react.MouseEventHandler<HTMLElement>;
        onContextMenu?: react.MouseEventHandler<HTMLElement>;
        onContextMenuCapture?: react.MouseEventHandler<HTMLElement>;
        onDoubleClick?: react.MouseEventHandler<HTMLElement>;
        onDoubleClickCapture?: react.MouseEventHandler<HTMLElement>;
        onDrag?: react.DragEventHandler<HTMLElement>;
        onDragCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnd?: react.DragEventHandler<HTMLElement>;
        onDragEndCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnter?: react.DragEventHandler<HTMLElement>;
        onDragEnterCapture?: react.DragEventHandler<HTMLElement>;
        onDragExit?: react.DragEventHandler<HTMLElement>;
        onDragExitCapture?: react.DragEventHandler<HTMLElement>;
        onDragLeave?: react.DragEventHandler<HTMLElement>;
        onDragLeaveCapture?: react.DragEventHandler<HTMLElement>;
        onDragOver?: react.DragEventHandler<HTMLElement>;
        onDragOverCapture?: react.DragEventHandler<HTMLElement>;
        onDragStart?: react.DragEventHandler<HTMLElement>;
        onDragStartCapture?: react.DragEventHandler<HTMLElement>;
        onDrop?: react.DragEventHandler<HTMLElement>;
        onDropCapture?: react.DragEventHandler<HTMLElement>;
        onMouseDown?: react.MouseEventHandler<HTMLElement>;
        onMouseDownCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseEnter?: react.MouseEventHandler<HTMLElement>;
        onMouseLeave?: react.MouseEventHandler<HTMLElement>;
        onMouseMove?: react.MouseEventHandler<HTMLElement>;
        onMouseMoveCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOut?: react.MouseEventHandler<HTMLElement>;
        onMouseOutCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOver?: react.MouseEventHandler<HTMLElement>;
        onMouseOverCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseUp?: react.MouseEventHandler<HTMLElement>;
        onMouseUpCapture?: react.MouseEventHandler<HTMLElement>;
        onSelect?: react.ReactEventHandler<HTMLElement>;
        onSelectCapture?: react.ReactEventHandler<HTMLElement>;
        onTouchCancel?: react.TouchEventHandler<HTMLElement>;
        onTouchCancelCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchEnd?: react.TouchEventHandler<HTMLElement>;
        onTouchEndCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchMove?: react.TouchEventHandler<HTMLElement>;
        onTouchMoveCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchStart?: react.TouchEventHandler<HTMLElement>;
        onTouchStartCapture?: react.TouchEventHandler<HTMLElement>;
        onPointerDown?: react.PointerEventHandler<HTMLElement>;
        onPointerDownCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerMove?: react.PointerEventHandler<HTMLElement>;
        onPointerMoveCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerUp?: react.PointerEventHandler<HTMLElement>;
        onPointerUpCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerCancel?: react.PointerEventHandler<HTMLElement>;
        onPointerCancelCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerEnter?: react.PointerEventHandler<HTMLElement>;
        onPointerLeave?: react.PointerEventHandler<HTMLElement>;
        onPointerOver?: react.PointerEventHandler<HTMLElement>;
        onPointerOverCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerOut?: react.PointerEventHandler<HTMLElement>;
        onPointerOutCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onScroll?: react.UIEventHandler<HTMLElement>;
        onScrollCapture?: react.UIEventHandler<HTMLElement>;
        onWheel?: react.WheelEventHandler<HTMLElement>;
        onWheelCapture?: react.WheelEventHandler<HTMLElement>;
        onAnimationStart?: react.AnimationEventHandler<HTMLElement>;
        onAnimationStartCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEnd?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEndCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIteration?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIterationCapture?: react.AnimationEventHandler<HTMLElement>;
        onTransitionEnd?: react.TransitionEventHandler<HTMLElement>;
        onTransitionEndCapture?: react.TransitionEventHandler<HTMLElement>;
    };
    thumbProps: {
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: react.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: react.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        exportparts?: string | undefined;
        part?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        children?: react.ReactNode | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: react.ClipboardEventHandler<HTMLElement>;
        onCopyCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCut?: react.ClipboardEventHandler<HTMLElement>;
        onCutCapture?: react.ClipboardEventHandler<HTMLElement>;
        onPaste?: react.ClipboardEventHandler<HTMLElement>;
        onPasteCapture?: react.ClipboardEventHandler<HTMLElement>;
        onCompositionEnd?: react.CompositionEventHandler<HTMLElement>;
        onCompositionEndCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStart?: react.CompositionEventHandler<HTMLElement>;
        onCompositionStartCapture?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdate?: react.CompositionEventHandler<HTMLElement>;
        onCompositionUpdateCapture?: react.CompositionEventHandler<HTMLElement>;
        onFocus?: react.FocusEventHandler<HTMLElement>;
        onFocusCapture?: react.FocusEventHandler<HTMLElement>;
        onBlur?: react.FocusEventHandler<HTMLElement>;
        onBlurCapture?: react.FocusEventHandler<HTMLElement>;
        onChange?: react.FormEventHandler<HTMLElement>;
        onChangeCapture?: react.FormEventHandler<HTMLElement>;
        onBeforeInput?: react.InputEventHandler<HTMLElement>;
        onBeforeInputCapture?: react.FormEventHandler<HTMLElement>;
        onInput?: react.FormEventHandler<HTMLElement>;
        onInputCapture?: react.FormEventHandler<HTMLElement>;
        onReset?: react.FormEventHandler<HTMLElement>;
        onResetCapture?: react.FormEventHandler<HTMLElement>;
        onSubmit?: react.FormEventHandler<HTMLElement>;
        onSubmitCapture?: react.FormEventHandler<HTMLElement>;
        onInvalid?: react.FormEventHandler<HTMLElement>;
        onInvalidCapture?: react.FormEventHandler<HTMLElement>;
        onLoad?: react.ReactEventHandler<HTMLElement>;
        onLoadCapture?: react.ReactEventHandler<HTMLElement>;
        onError?: react.ReactEventHandler<HTMLElement>;
        onErrorCapture?: react.ReactEventHandler<HTMLElement>;
        onKeyDown?: react.KeyboardEventHandler<HTMLElement>;
        onKeyDownCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPress?: react.KeyboardEventHandler<HTMLElement>;
        onKeyPressCapture?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUp?: react.KeyboardEventHandler<HTMLElement>;
        onKeyUpCapture?: react.KeyboardEventHandler<HTMLElement>;
        onAbort?: react.ReactEventHandler<HTMLElement>;
        onAbortCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlay?: react.ReactEventHandler<HTMLElement>;
        onCanPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThrough?: react.ReactEventHandler<HTMLElement>;
        onCanPlayThroughCapture?: react.ReactEventHandler<HTMLElement>;
        onDurationChange?: react.ReactEventHandler<HTMLElement>;
        onDurationChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onEmptied?: react.ReactEventHandler<HTMLElement>;
        onEmptiedCapture?: react.ReactEventHandler<HTMLElement>;
        onEncrypted?: react.ReactEventHandler<HTMLElement>;
        onEncryptedCapture?: react.ReactEventHandler<HTMLElement>;
        onEnded?: react.ReactEventHandler<HTMLElement>;
        onEndedCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedData?: react.ReactEventHandler<HTMLElement>;
        onLoadedDataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadata?: react.ReactEventHandler<HTMLElement>;
        onLoadedMetadataCapture?: react.ReactEventHandler<HTMLElement>;
        onLoadStart?: react.ReactEventHandler<HTMLElement>;
        onLoadStartCapture?: react.ReactEventHandler<HTMLElement>;
        onPause?: react.ReactEventHandler<HTMLElement>;
        onPauseCapture?: react.ReactEventHandler<HTMLElement>;
        onPlay?: react.ReactEventHandler<HTMLElement>;
        onPlayCapture?: react.ReactEventHandler<HTMLElement>;
        onPlaying?: react.ReactEventHandler<HTMLElement>;
        onPlayingCapture?: react.ReactEventHandler<HTMLElement>;
        onProgress?: react.ReactEventHandler<HTMLElement>;
        onProgressCapture?: react.ReactEventHandler<HTMLElement>;
        onRateChange?: react.ReactEventHandler<HTMLElement>;
        onRateChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeked?: react.ReactEventHandler<HTMLElement>;
        onSeekedCapture?: react.ReactEventHandler<HTMLElement>;
        onSeeking?: react.ReactEventHandler<HTMLElement>;
        onSeekingCapture?: react.ReactEventHandler<HTMLElement>;
        onStalled?: react.ReactEventHandler<HTMLElement>;
        onStalledCapture?: react.ReactEventHandler<HTMLElement>;
        onSuspend?: react.ReactEventHandler<HTMLElement>;
        onSuspendCapture?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdate?: react.ReactEventHandler<HTMLElement>;
        onTimeUpdateCapture?: react.ReactEventHandler<HTMLElement>;
        onVolumeChange?: react.ReactEventHandler<HTMLElement>;
        onVolumeChangeCapture?: react.ReactEventHandler<HTMLElement>;
        onWaiting?: react.ReactEventHandler<HTMLElement>;
        onWaitingCapture?: react.ReactEventHandler<HTMLElement>;
        onAuxClick?: react.MouseEventHandler<HTMLElement>;
        onAuxClickCapture?: react.MouseEventHandler<HTMLElement>;
        onClick?: react.MouseEventHandler<HTMLElement>;
        onClickCapture?: react.MouseEventHandler<HTMLElement>;
        onContextMenu?: react.MouseEventHandler<HTMLElement>;
        onContextMenuCapture?: react.MouseEventHandler<HTMLElement>;
        onDoubleClick?: react.MouseEventHandler<HTMLElement>;
        onDoubleClickCapture?: react.MouseEventHandler<HTMLElement>;
        onDrag?: react.DragEventHandler<HTMLElement>;
        onDragCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnd?: react.DragEventHandler<HTMLElement>;
        onDragEndCapture?: react.DragEventHandler<HTMLElement>;
        onDragEnter?: react.DragEventHandler<HTMLElement>;
        onDragEnterCapture?: react.DragEventHandler<HTMLElement>;
        onDragExit?: react.DragEventHandler<HTMLElement>;
        onDragExitCapture?: react.DragEventHandler<HTMLElement>;
        onDragLeave?: react.DragEventHandler<HTMLElement>;
        onDragLeaveCapture?: react.DragEventHandler<HTMLElement>;
        onDragOver?: react.DragEventHandler<HTMLElement>;
        onDragOverCapture?: react.DragEventHandler<HTMLElement>;
        onDragStart?: react.DragEventHandler<HTMLElement>;
        onDragStartCapture?: react.DragEventHandler<HTMLElement>;
        onDrop?: react.DragEventHandler<HTMLElement>;
        onDropCapture?: react.DragEventHandler<HTMLElement>;
        onMouseDown?: react.MouseEventHandler<HTMLElement>;
        onMouseDownCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseEnter?: react.MouseEventHandler<HTMLElement>;
        onMouseLeave?: react.MouseEventHandler<HTMLElement>;
        onMouseMove?: react.MouseEventHandler<HTMLElement>;
        onMouseMoveCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOut?: react.MouseEventHandler<HTMLElement>;
        onMouseOutCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseOver?: react.MouseEventHandler<HTMLElement>;
        onMouseOverCapture?: react.MouseEventHandler<HTMLElement>;
        onMouseUp?: react.MouseEventHandler<HTMLElement>;
        onMouseUpCapture?: react.MouseEventHandler<HTMLElement>;
        onSelect?: react.ReactEventHandler<HTMLElement>;
        onSelectCapture?: react.ReactEventHandler<HTMLElement>;
        onTouchCancel?: react.TouchEventHandler<HTMLElement>;
        onTouchCancelCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchEnd?: react.TouchEventHandler<HTMLElement>;
        onTouchEndCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchMove?: react.TouchEventHandler<HTMLElement>;
        onTouchMoveCapture?: react.TouchEventHandler<HTMLElement>;
        onTouchStart?: react.TouchEventHandler<HTMLElement>;
        onTouchStartCapture?: react.TouchEventHandler<HTMLElement>;
        onPointerDown?: react.PointerEventHandler<HTMLElement>;
        onPointerDownCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerMove?: react.PointerEventHandler<HTMLElement>;
        onPointerMoveCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerUp?: react.PointerEventHandler<HTMLElement>;
        onPointerUpCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerCancel?: react.PointerEventHandler<HTMLElement>;
        onPointerCancelCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerEnter?: react.PointerEventHandler<HTMLElement>;
        onPointerLeave?: react.PointerEventHandler<HTMLElement>;
        onPointerOver?: react.PointerEventHandler<HTMLElement>;
        onPointerOverCapture?: react.PointerEventHandler<HTMLElement>;
        onPointerOut?: react.PointerEventHandler<HTMLElement>;
        onPointerOutCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onGotPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCapture?: react.PointerEventHandler<HTMLElement>;
        onLostPointerCaptureCapture?: react.PointerEventHandler<HTMLElement>;
        onScroll?: react.UIEventHandler<HTMLElement>;
        onScrollCapture?: react.UIEventHandler<HTMLElement>;
        onWheel?: react.WheelEventHandler<HTMLElement>;
        onWheelCapture?: react.WheelEventHandler<HTMLElement>;
        onAnimationStart?: react.AnimationEventHandler<HTMLElement>;
        onAnimationStartCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEnd?: react.AnimationEventHandler<HTMLElement>;
        onAnimationEndCapture?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIteration?: react.AnimationEventHandler<HTMLElement>;
        onAnimationIterationCapture?: react.AnimationEventHandler<HTMLElement>;
        onTransitionEnd?: react.TransitionEventHandler<HTMLElement>;
        onTransitionEndCapture?: react.TransitionEventHandler<HTMLElement>;
    };
    hiddenInputProps: {
        disabled?: boolean | undefined;
        required?: boolean | undefined;
        checked?: boolean | undefined;
        defaultChecked?: boolean | undefined;
        defaultValue?: string | number | readonly string[] | undefined;
        suppressContentEditableWarning?: boolean | undefined;
        suppressHydrationWarning?: boolean | undefined;
        accessKey?: string | undefined;
        autoCapitalize?: "off" | "none" | "on" | "sentences" | "words" | "characters" | undefined | (string & {});
        autoFocus?: boolean | undefined;
        className?: string | undefined;
        contentEditable?: (boolean | "true" | "false") | "inherit" | "plaintext-only" | undefined;
        contextMenu?: string | undefined;
        dir?: string | undefined;
        draggable?: (boolean | "true" | "false") | undefined;
        enterKeyHint?: "enter" | "done" | "go" | "next" | "previous" | "search" | "send" | undefined;
        hidden?: boolean | undefined;
        id?: string | undefined;
        lang?: string | undefined;
        nonce?: string | undefined;
        slot?: string | undefined;
        spellCheck?: (boolean | "true" | "false") | undefined;
        style?: react.CSSProperties | undefined;
        tabIndex?: number | undefined;
        title?: string | undefined;
        translate?: "yes" | "no" | undefined;
        radioGroup?: string | undefined;
        role?: react.AriaRole | undefined;
        about?: string | undefined;
        content?: string | undefined;
        datatype?: string | undefined;
        inlist?: any;
        prefix?: string | undefined;
        property?: string | undefined;
        rel?: string | undefined;
        resource?: string | undefined;
        rev?: string | undefined;
        typeof?: string | undefined;
        vocab?: string | undefined;
        autoCorrect?: string | undefined;
        autoSave?: string | undefined;
        color?: string | undefined;
        itemProp?: string | undefined;
        itemScope?: boolean | undefined;
        itemType?: string | undefined;
        itemID?: string | undefined;
        itemRef?: string | undefined;
        results?: number | undefined;
        security?: string | undefined;
        unselectable?: "on" | "off" | undefined;
        inputMode?: "none" | "text" | "tel" | "url" | "email" | "numeric" | "decimal" | "search" | undefined;
        is?: string | undefined;
        exportparts?: string | undefined;
        part?: string | undefined;
        "aria-activedescendant"?: string | undefined;
        "aria-atomic"?: (boolean | "true" | "false") | undefined;
        "aria-autocomplete"?: "none" | "inline" | "list" | "both" | undefined;
        "aria-braillelabel"?: string | undefined;
        "aria-brailleroledescription"?: string | undefined;
        "aria-busy"?: (boolean | "true" | "false") | undefined;
        "aria-checked"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-colcount"?: number | undefined;
        "aria-colindex"?: number | undefined;
        "aria-colindextext"?: string | undefined;
        "aria-colspan"?: number | undefined;
        "aria-controls"?: string | undefined;
        "aria-current"?: boolean | "false" | "true" | "page" | "step" | "location" | "date" | "time" | undefined;
        "aria-describedby"?: string | undefined;
        "aria-description"?: string | undefined;
        "aria-details"?: string | undefined;
        "aria-disabled"?: (boolean | "true" | "false") | undefined;
        "aria-dropeffect"?: "none" | "copy" | "execute" | "link" | "move" | "popup" | undefined;
        "aria-errormessage"?: string | undefined;
        "aria-expanded"?: (boolean | "true" | "false") | undefined;
        "aria-flowto"?: string | undefined;
        "aria-grabbed"?: (boolean | "true" | "false") | undefined;
        "aria-haspopup"?: boolean | "false" | "true" | "menu" | "listbox" | "tree" | "grid" | "dialog" | undefined;
        "aria-hidden"?: (boolean | "true" | "false") | undefined;
        "aria-invalid"?: boolean | "false" | "true" | "grammar" | "spelling" | undefined;
        "aria-keyshortcuts"?: string | undefined;
        "aria-label"?: string | undefined;
        "aria-labelledby"?: string | undefined;
        "aria-level"?: number | undefined;
        "aria-live"?: "off" | "assertive" | "polite" | undefined;
        "aria-modal"?: (boolean | "true" | "false") | undefined;
        "aria-multiline"?: (boolean | "true" | "false") | undefined;
        "aria-multiselectable"?: (boolean | "true" | "false") | undefined;
        "aria-orientation"?: "horizontal" | "vertical" | undefined;
        "aria-owns"?: string | undefined;
        "aria-placeholder"?: string | undefined;
        "aria-posinset"?: number | undefined;
        "aria-pressed"?: boolean | "false" | "mixed" | "true" | undefined;
        "aria-readonly"?: (boolean | "true" | "false") | undefined;
        "aria-relevant"?: "additions" | "additions removals" | "additions text" | "all" | "removals" | "removals additions" | "removals text" | "text" | "text additions" | "text removals" | undefined;
        "aria-required"?: (boolean | "true" | "false") | undefined;
        "aria-roledescription"?: string | undefined;
        "aria-rowcount"?: number | undefined;
        "aria-rowindex"?: number | undefined;
        "aria-rowindextext"?: string | undefined;
        "aria-rowspan"?: number | undefined;
        "aria-selected"?: (boolean | "true" | "false") | undefined;
        "aria-setsize"?: number | undefined;
        "aria-sort"?: "none" | "ascending" | "descending" | "other" | undefined;
        "aria-valuemax"?: number | undefined;
        "aria-valuemin"?: number | undefined;
        "aria-valuenow"?: number | undefined;
        "aria-valuetext"?: string | undefined;
        children?: react.ReactNode | undefined;
        dangerouslySetInnerHTML?: {
            __html: string | TrustedHTML;
        } | undefined;
        onCopy?: react.ClipboardEventHandler<HTMLInputElement>;
        onCopyCapture?: react.ClipboardEventHandler<HTMLInputElement>;
        onCut?: react.ClipboardEventHandler<HTMLInputElement>;
        onCutCapture?: react.ClipboardEventHandler<HTMLInputElement>;
        onPaste?: react.ClipboardEventHandler<HTMLInputElement>;
        onPasteCapture?: react.ClipboardEventHandler<HTMLInputElement>;
        onCompositionEnd?: react.CompositionEventHandler<HTMLInputElement>;
        onCompositionEndCapture?: react.CompositionEventHandler<HTMLInputElement>;
        onCompositionStart?: react.CompositionEventHandler<HTMLInputElement>;
        onCompositionStartCapture?: react.CompositionEventHandler<HTMLInputElement>;
        onCompositionUpdate?: react.CompositionEventHandler<HTMLInputElement>;
        onCompositionUpdateCapture?: react.CompositionEventHandler<HTMLInputElement>;
        onFocus?: react.FocusEventHandler<HTMLInputElement>;
        onFocusCapture?: react.FocusEventHandler<HTMLInputElement>;
        onBlur?: react.FocusEventHandler<HTMLInputElement>;
        onBlurCapture?: react.FocusEventHandler<HTMLInputElement>;
        onChange?: react.ChangeEventHandler<HTMLInputElement>;
        onChangeCapture?: react.FormEventHandler<HTMLInputElement>;
        onBeforeInput?: react.InputEventHandler<HTMLInputElement>;
        onBeforeInputCapture?: react.FormEventHandler<HTMLInputElement>;
        onInput?: react.FormEventHandler<HTMLInputElement>;
        onInputCapture?: react.FormEventHandler<HTMLInputElement>;
        onReset?: react.FormEventHandler<HTMLInputElement>;
        onResetCapture?: react.FormEventHandler<HTMLInputElement>;
        onSubmit?: react.FormEventHandler<HTMLInputElement>;
        onSubmitCapture?: react.FormEventHandler<HTMLInputElement>;
        onInvalid?: react.FormEventHandler<HTMLInputElement>;
        onInvalidCapture?: react.FormEventHandler<HTMLInputElement>;
        onLoad?: react.ReactEventHandler<HTMLInputElement>;
        onLoadCapture?: react.ReactEventHandler<HTMLInputElement>;
        onError?: react.ReactEventHandler<HTMLInputElement>;
        onErrorCapture?: react.ReactEventHandler<HTMLInputElement>;
        onKeyDown?: react.KeyboardEventHandler<HTMLInputElement>;
        onKeyDownCapture?: react.KeyboardEventHandler<HTMLInputElement>;
        onKeyPress?: react.KeyboardEventHandler<HTMLInputElement>;
        onKeyPressCapture?: react.KeyboardEventHandler<HTMLInputElement>;
        onKeyUp?: react.KeyboardEventHandler<HTMLInputElement>;
        onKeyUpCapture?: react.KeyboardEventHandler<HTMLInputElement>;
        onAbort?: react.ReactEventHandler<HTMLInputElement>;
        onAbortCapture?: react.ReactEventHandler<HTMLInputElement>;
        onCanPlay?: react.ReactEventHandler<HTMLInputElement>;
        onCanPlayCapture?: react.ReactEventHandler<HTMLInputElement>;
        onCanPlayThrough?: react.ReactEventHandler<HTMLInputElement>;
        onCanPlayThroughCapture?: react.ReactEventHandler<HTMLInputElement>;
        onDurationChange?: react.ReactEventHandler<HTMLInputElement>;
        onDurationChangeCapture?: react.ReactEventHandler<HTMLInputElement>;
        onEmptied?: react.ReactEventHandler<HTMLInputElement>;
        onEmptiedCapture?: react.ReactEventHandler<HTMLInputElement>;
        onEncrypted?: react.ReactEventHandler<HTMLInputElement>;
        onEncryptedCapture?: react.ReactEventHandler<HTMLInputElement>;
        onEnded?: react.ReactEventHandler<HTMLInputElement>;
        onEndedCapture?: react.ReactEventHandler<HTMLInputElement>;
        onLoadedData?: react.ReactEventHandler<HTMLInputElement>;
        onLoadedDataCapture?: react.ReactEventHandler<HTMLInputElement>;
        onLoadedMetadata?: react.ReactEventHandler<HTMLInputElement>;
        onLoadedMetadataCapture?: react.ReactEventHandler<HTMLInputElement>;
        onLoadStart?: react.ReactEventHandler<HTMLInputElement>;
        onLoadStartCapture?: react.ReactEventHandler<HTMLInputElement>;
        onPause?: react.ReactEventHandler<HTMLInputElement>;
        onPauseCapture?: react.ReactEventHandler<HTMLInputElement>;
        onPlay?: react.ReactEventHandler<HTMLInputElement>;
        onPlayCapture?: react.ReactEventHandler<HTMLInputElement>;
        onPlaying?: react.ReactEventHandler<HTMLInputElement>;
        onPlayingCapture?: react.ReactEventHandler<HTMLInputElement>;
        onProgress?: react.ReactEventHandler<HTMLInputElement>;
        onProgressCapture?: react.ReactEventHandler<HTMLInputElement>;
        onRateChange?: react.ReactEventHandler<HTMLInputElement>;
        onRateChangeCapture?: react.ReactEventHandler<HTMLInputElement>;
        onSeeked?: react.ReactEventHandler<HTMLInputElement>;
        onSeekedCapture?: react.ReactEventHandler<HTMLInputElement>;
        onSeeking?: react.ReactEventHandler<HTMLInputElement>;
        onSeekingCapture?: react.ReactEventHandler<HTMLInputElement>;
        onStalled?: react.ReactEventHandler<HTMLInputElement>;
        onStalledCapture?: react.ReactEventHandler<HTMLInputElement>;
        onSuspend?: react.ReactEventHandler<HTMLInputElement>;
        onSuspendCapture?: react.ReactEventHandler<HTMLInputElement>;
        onTimeUpdate?: react.ReactEventHandler<HTMLInputElement>;
        onTimeUpdateCapture?: react.ReactEventHandler<HTMLInputElement>;
        onVolumeChange?: react.ReactEventHandler<HTMLInputElement>;
        onVolumeChangeCapture?: react.ReactEventHandler<HTMLInputElement>;
        onWaiting?: react.ReactEventHandler<HTMLInputElement>;
        onWaitingCapture?: react.ReactEventHandler<HTMLInputElement>;
        onAuxClick?: react.MouseEventHandler<HTMLInputElement>;
        onAuxClickCapture?: react.MouseEventHandler<HTMLInputElement>;
        onClick?: react.MouseEventHandler<HTMLInputElement>;
        onClickCapture?: react.MouseEventHandler<HTMLInputElement>;
        onContextMenu?: react.MouseEventHandler<HTMLInputElement>;
        onContextMenuCapture?: react.MouseEventHandler<HTMLInputElement>;
        onDoubleClick?: react.MouseEventHandler<HTMLInputElement>;
        onDoubleClickCapture?: react.MouseEventHandler<HTMLInputElement>;
        onDrag?: react.DragEventHandler<HTMLInputElement>;
        onDragCapture?: react.DragEventHandler<HTMLInputElement>;
        onDragEnd?: react.DragEventHandler<HTMLInputElement>;
        onDragEndCapture?: react.DragEventHandler<HTMLInputElement>;
        onDragEnter?: react.DragEventHandler<HTMLInputElement>;
        onDragEnterCapture?: react.DragEventHandler<HTMLInputElement>;
        onDragExit?: react.DragEventHandler<HTMLInputElement>;
        onDragExitCapture?: react.DragEventHandler<HTMLInputElement>;
        onDragLeave?: react.DragEventHandler<HTMLInputElement>;
        onDragLeaveCapture?: react.DragEventHandler<HTMLInputElement>;
        onDragOver?: react.DragEventHandler<HTMLInputElement>;
        onDragOverCapture?: react.DragEventHandler<HTMLInputElement>;
        onDragStart?: react.DragEventHandler<HTMLInputElement>;
        onDragStartCapture?: react.DragEventHandler<HTMLInputElement>;
        onDrop?: react.DragEventHandler<HTMLInputElement>;
        onDropCapture?: react.DragEventHandler<HTMLInputElement>;
        onMouseDown?: react.MouseEventHandler<HTMLInputElement>;
        onMouseDownCapture?: react.MouseEventHandler<HTMLInputElement>;
        onMouseEnter?: react.MouseEventHandler<HTMLInputElement>;
        onMouseLeave?: react.MouseEventHandler<HTMLInputElement>;
        onMouseMove?: react.MouseEventHandler<HTMLInputElement>;
        onMouseMoveCapture?: react.MouseEventHandler<HTMLInputElement>;
        onMouseOut?: react.MouseEventHandler<HTMLInputElement>;
        onMouseOutCapture?: react.MouseEventHandler<HTMLInputElement>;
        onMouseOver?: react.MouseEventHandler<HTMLInputElement>;
        onMouseOverCapture?: react.MouseEventHandler<HTMLInputElement>;
        onMouseUp?: react.MouseEventHandler<HTMLInputElement>;
        onMouseUpCapture?: react.MouseEventHandler<HTMLInputElement>;
        onSelect?: react.ReactEventHandler<HTMLInputElement>;
        onSelectCapture?: react.ReactEventHandler<HTMLInputElement>;
        onTouchCancel?: react.TouchEventHandler<HTMLInputElement>;
        onTouchCancelCapture?: react.TouchEventHandler<HTMLInputElement>;
        onTouchEnd?: react.TouchEventHandler<HTMLInputElement>;
        onTouchEndCapture?: react.TouchEventHandler<HTMLInputElement>;
        onTouchMove?: react.TouchEventHandler<HTMLInputElement>;
        onTouchMoveCapture?: react.TouchEventHandler<HTMLInputElement>;
        onTouchStart?: react.TouchEventHandler<HTMLInputElement>;
        onTouchStartCapture?: react.TouchEventHandler<HTMLInputElement>;
        onPointerDown?: react.PointerEventHandler<HTMLInputElement>;
        onPointerDownCapture?: react.PointerEventHandler<HTMLInputElement>;
        onPointerMove?: react.PointerEventHandler<HTMLInputElement>;
        onPointerMoveCapture?: react.PointerEventHandler<HTMLInputElement>;
        onPointerUp?: react.PointerEventHandler<HTMLInputElement>;
        onPointerUpCapture?: react.PointerEventHandler<HTMLInputElement>;
        onPointerCancel?: react.PointerEventHandler<HTMLInputElement>;
        onPointerCancelCapture?: react.PointerEventHandler<HTMLInputElement>;
        onPointerEnter?: react.PointerEventHandler<HTMLInputElement>;
        onPointerLeave?: react.PointerEventHandler<HTMLInputElement>;
        onPointerOver?: react.PointerEventHandler<HTMLInputElement>;
        onPointerOverCapture?: react.PointerEventHandler<HTMLInputElement>;
        onPointerOut?: react.PointerEventHandler<HTMLInputElement>;
        onPointerOutCapture?: react.PointerEventHandler<HTMLInputElement>;
        onGotPointerCapture?: react.PointerEventHandler<HTMLInputElement>;
        onGotPointerCaptureCapture?: react.PointerEventHandler<HTMLInputElement>;
        onLostPointerCapture?: react.PointerEventHandler<HTMLInputElement>;
        onLostPointerCaptureCapture?: react.PointerEventHandler<HTMLInputElement>;
        onScroll?: react.UIEventHandler<HTMLInputElement>;
        onScrollCapture?: react.UIEventHandler<HTMLInputElement>;
        onWheel?: react.WheelEventHandler<HTMLInputElement>;
        onWheelCapture?: react.WheelEventHandler<HTMLInputElement>;
        onAnimationStart?: react.AnimationEventHandler<HTMLInputElement>;
        onAnimationStartCapture?: react.AnimationEventHandler<HTMLInputElement>;
        onAnimationEnd?: react.AnimationEventHandler<HTMLInputElement>;
        onAnimationEndCapture?: react.AnimationEventHandler<HTMLInputElement>;
        onAnimationIteration?: react.AnimationEventHandler<HTMLInputElement>;
        onAnimationIterationCapture?: react.AnimationEventHandler<HTMLInputElement>;
        onTransitionEnd?: react.TransitionEventHandler<HTMLInputElement>;
        onTransitionEndCapture?: react.TransitionEventHandler<HTMLInputElement>;
        accept?: string | undefined;
        alt?: string | undefined;
        autoComplete?: react.HTMLInputAutoCompleteAttribute | undefined;
        capture?: boolean | "user" | "environment" | undefined;
        form?: string | undefined;
        formAction?: string | react.DO_NOT_USE_OR_YOU_WILL_BE_FIRED_EXPERIMENTAL_FORM_ACTIONS[keyof react.DO_NOT_USE_OR_YOU_WILL_BE_FIRED_EXPERIMENTAL_FORM_ACTIONS] | undefined;
        formEncType?: string | undefined;
        formMethod?: string | undefined;
        formNoValidate?: boolean | undefined;
        formTarget?: string | undefined;
        height?: number | string | undefined;
        list?: string | undefined;
        max?: number | string | undefined;
        maxLength?: number | undefined;
        min?: number | string | undefined;
        minLength?: number | undefined;
        multiple?: boolean | undefined;
        name?: string | undefined;
        pattern?: string | undefined;
        placeholder?: string | undefined;
        readOnly?: boolean | undefined;
        size?: number | undefined;
        src?: string | undefined;
        step?: number | string | undefined;
        type?: react.HTMLInputTypeAttribute | undefined;
        value?: string | readonly string[] | number | undefined;
        width?: number | string | undefined;
    };
};

interface SwitchRootProps extends UseSwitchProps, PrimitiveProps, react.HTMLAttributes<HTMLLabelElement> {
}
declare const SwitchRoot: react.ForwardRefExoticComponent<SwitchRootProps & react.RefAttributes<HTMLLabelElement>>;
interface SwitchControlProps extends PrimitiveProps, react.HTMLAttributes<HTMLDivElement> {
}
declare const SwitchControl: react.ForwardRefExoticComponent<SwitchControlProps & react.RefAttributes<HTMLDivElement>>;
interface SwitchThumbProps extends PrimitiveProps, react.HTMLAttributes<HTMLDivElement> {
}
declare const SwitchThumb: react.ForwardRefExoticComponent<SwitchThumbProps & react.RefAttributes<HTMLDivElement>>;
interface SwitchHiddenInputProps extends PrimitiveProps, react.InputHTMLAttributes<HTMLInputElement> {
}
declare const SwitchHiddenInput: react.ForwardRefExoticComponent<SwitchHiddenInputProps & react.RefAttributes<HTMLInputElement>>;

interface UseSwitchContext extends UseSwitchReturn {
}
declare function useSwitchContext<T extends boolean | undefined = true>({ strict, }?: {
    strict?: T;
}): T extends false ? UseSwitchContext | null : UseSwitchContext;

declare namespace Switch_namespace {
  export { SwitchControl as Control, SwitchHiddenInput as HiddenInput, SwitchRoot as Root, SwitchThumb as Thumb };
  export type { SwitchControlProps as ControlProps, SwitchHiddenInputProps as HiddenInputProps, SwitchRootProps as RootProps, SwitchThumbProps as ThumbProps };
}

export { Switch_namespace as Switch, SwitchControl, SwitchHiddenInput, SwitchRoot, SwitchThumb, useSwitchContext };
export type { SwitchControlProps, SwitchHiddenInputProps, SwitchRootProps, SwitchThumbProps, UseSwitchContext };
